# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/public/Share/qinlingbo/python/maya_script/transfer_uv/transfer_uv_tools.ui'
#
# Created: Fri Feb 22 16:12:59 2019
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

#from PyQt4 import QtCore, QtGui
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 175)
        self.horizontalLayout = QHBoxLayout(Form)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.group_transfer_uv = QWidget()
        self.group_transfer_uv.setObjectName("group_transfer_uv")
        self.verticalLayout_2 = QVBoxLayout(self.group_transfer_uv)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QSpacerItem(20, 120, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.group_teans_uv_button = QPushButton(self.group_transfer_uv)
        self.group_teans_uv_button.setObjectName("group_teans_uv_button")
        self.verticalLayout_2.addWidget(self.group_teans_uv_button)
        spacerItem1 = QSpacerItem(20, 120, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.group_transfer_uv, "")
        self.select_from_object = QWidget()
        self.select_from_object.setObjectName("select_from_object")
        self.horizontalLayout_2 = QHBoxLayout(self.select_from_object)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QLabel(self.select_from_object)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.group_groupName = QLineEdit(self.select_from_object)
        self.group_groupName.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_groupName.sizePolicy().hasHeightForWidth())
        self.group_groupName.setSizePolicy(sizePolicy)
        self.group_groupName.setObjectName("group_groupName")
        self.horizontalLayout_3.addWidget(self.group_groupName)
        self.anylize_group_button = QPushButton(self.select_from_object)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anylize_group_button.sizePolicy().hasHeightForWidth())
        self.anylize_group_button.setSizePolicy(sizePolicy)
        self.anylize_group_button.setObjectName("anylize_group_button")
        self.horizontalLayout_3.addWidget(self.anylize_group_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.select_same_in_group_button = QPushButton(self.select_from_object)
        self.select_same_in_group_button.setObjectName("select_same_in_group_button")
        self.horizontalLayout_5.addWidget(self.select_same_in_group_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.transfer_uv_group_button = QPushButton(self.select_from_object)
        self.transfer_uv_group_button.setObjectName("transfer_uv_group_button")
        self.horizontalLayout_4.addWidget(self.transfer_uv_group_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.select_from_object, "")
        self.select_from_group = QWidget()
        self.select_from_group.setObjectName("select_from_group")
        self.horizontalLayout_6 = QHBoxLayout(self.select_from_group)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QLabel(self.select_from_group)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.groupName = QLineEdit(self.select_from_group)
        self.groupName.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupName.sizePolicy().hasHeightForWidth())
        self.groupName.setSizePolicy(sizePolicy)
        self.groupName.setDragEnabled(True)
        self.groupName.setObjectName("groupName")
        self.horizontalLayout_7.addWidget(self.groupName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.look_objects_by_topu_button = QPushButton(self.select_from_group)
        self.look_objects_by_topu_button.setObjectName("look_objects_by_topu_button")
        self.horizontalLayout_9.addWidget(self.look_objects_by_topu_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.transfer_uv_by_object_button = QPushButton(self.select_from_group)
        self.transfer_uv_by_object_button.setObjectName("transfer_uv_by_object_button")
        self.horizontalLayout_8.addWidget(self.transfer_uv_by_object_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.select_from_group, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", "UV_Tools", None, ))
        self.group_teans_uv_button.setText(QCoreApplication.translate("Form", "transform_uv_by_group", None, ))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.group_transfer_uv), QCoreApplication.translate("Form", "transform_uv_by_group", None, ))
        self.label.setText(QCoreApplication.translate("Form", "group", None, ))
        self.anylize_group_button.setText(QCoreApplication.translate("Form", "analyze", None, ))
        self.select_same_in_group_button.setText(QCoreApplication.translate("Form", "select unique ojects", None, ))
        self.transfer_uv_group_button.setText(QCoreApplication.translate("Form", "tranform_uv", None, ))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.select_from_object), QCoreApplication.translate("Form", "look for unique object", None, ))
        self.label_2.setText(QCoreApplication.translate("Form", "group", None, ))
        self.look_objects_by_topu_button.setText(QCoreApplication.translate("Form", "look for unique object", None, ))
        self.transfer_uv_by_object_button.setText(QCoreApplication.translate("Form", "tranform_uv", None, ))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.select_from_group),  "select same topu objects")

