pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["animrescue_advancedrecovery_en.htm","AnimRescue Advanced Recovery","Advanced Recovery Wizard: Right click on minitoolBox icon and select \"Advanced Recovery Wizard..\" . Or you can choose \"Automatic Recovery Wizard.....",""],
["animrescue_autorecovery_en.htm","AnimRescue Auto-Recovery","Automatic Recovery Wizard: The automatic recovery wizard, shows you three recovery mode: Animation recovery mode , connection recovery mode and au...",""],
["animrescue_backup_en.htm","AnimRescue Backup","Realtime Animation Backup : The No.01 pain in ass for animator could be ,after hours of working, the animation just gone after maya crash, windows...",""],
["annotation_display_en.htm","Annotation FrameCounter","Annotation frame counter : Click to create a simply annotation based frame counter. If u have created it , click it to delete. How to do this: 1.C...",""],
["assetlibrary_en.htm","MG-AssetLibrary","MG-Asset Library: Click to open MG-AssetLibrary. The tool serves as an information db of Maya assets, for layout artist. It is supposed to be brid...",""],
["assetlib_addcategory_en.htm","Add Asset Category","Adding Category: After a asset project is created, you need to add category to it to continue. A category ,is a easy concept, say we often divide ...",""],
["assetlib_batchmakeicon_en.htm","Batch Make PreviewImages","Batch Making Asset Preview Images: Check on some assets that you want to make their preview images, use one of the following entries to open up th...",""],
["assetlib_createassetitem_en.htm","New Asset Item","New Asset item: Press the button on MG-Asset Library UI to open this window: If you select a reference node then open this dialog, the UI will aut...",""],
["assetlib_createproject_en.htm","Create Library Project","How to create new asset project: Click the top left new project button . Project menu/New Project.. If no project available in local side, press t...",""],
["assetlib_melapi_en.htm","AssetLib Mel API","Asset Library MEL API: The MEL API of MG-Asset Library. You could use these mel global procedures to create, manage and use the asset libraries in...",""],
["assetlib_previewpanel_en.htm","Preview Panel","Preview mode in MG-Asset Library: Press the button on Asset Library to switch the display mode from simple mode to preview mode. Previous / Next A...",""],
["assetlib_py_api_en.htm","AssetLib Py API","Asset Library Python API: The python API of MG-Asset Library. You could use these python function and classes to create, manage and use the asset ...",""],
["assetlib_sharing_en.htm","Library Sharing","Share the Asset Library: 1.The IT manager, make a folder in the server, the folder is only writable to someone who need to manage the global libra...",""],
["assetlib_useasset_en.htm","Using Library","Make MA: Check on some asset items in tools, try one of these: Click the Make MA button at the bottom of the tool UI. Operation Menu / Make MA.. M...",""],
["attr_switch_en.htm","Attribute-Switcher","Attr-Switcher without popping: With some quick config, It will help you switch some attributes without popping. It is good to use it to switch fol...",""],
["backup_restore_animation_en.htm","BackUP/Restore animation","Backup / Restore animation: Click to backup / restore the animation of current selection. The animation will be kept by some locators. Use this be...",""],
["batchscanassetitems_en.htm","Batch Add Asset Items","Batch adding asset items from a directory: Press the button on MG-Asset Library UI to open this window: Scan sub-folder as well: Scan all sub-dire...",""],
["bdtool_en.htm","BD Tool","BD Tool: Insert / edit BD key between two keyframes via different percentage. How to Use: 1.Open Keyframe tools, click on BD tool title if it&#39;s fo...",""],
["bioconstraint_en.htm","Bio-Constraint","Bio-Constraint: Generate a mechanism that bio-constrain two transform nodes based on Maya&#39;s default nodes. Bio-Constraint Workflow: 1.Select two c...",""],
["cam2dviewer_en.htm","Cam2dViewer","Cam2dViewer: Click to set current tool to cam2dViewer tool. Use it to browse your 3D view in 2D way,such as zoom in / out / pan / rotate . To load...",""],
["camswitch_en.htm","cam Swicher","MG-camSwitch: One key switch the camera of current active view. By default it will switch between prep and front camera. The switch queue is user-...",""],
["configviewset_en.htm","Config ViewSet","ViewSet config: Click to load viewSet config to config two or three view port switch. How to load viewSet config ( Do one of the following ) : Cli...",""],
["config_mgtools_en.htm","Config MGtools","MGTools Conifg: Customize MGTools hotkeys ,autoloading issues and install MGTools shelves, etc. To load MGTools Config (Do one of the following): ...",""],
["constraint_lister_en.htm","Constraint Lister","Constraint lister: Load constraint lister to manager the constraint of the constraint object. Or click the icon in your Maya shelves (If U have in...",""],
["constraint_tool_en.htm","ConstraintTools","Constraint tools: This tool is written to improve the efficiency of constraining. Popup Menu: Find Joint via vertex : Select the smooth bind joint...",""],
["copyconstraintbetweenmaya_en.htm","Copy/Paste Constraint","Copy/paste Constraint Between Maya: Copy and paste constraint and its related keyframes between different Maya scenes. This feature shares the sam...",""],
["copypasteanimpose_en.htm","Copy/Paste Anim&#38;Pose","Copy Anim/Pose Pro: Click to load copy Anim/Pose pro to copy/paste animation/pose between different maya. How to use: 1.Open tool. 2.Select the ob...",""],
["displaylayer_set_en.htm","DisplayLayerSet","Display layer set manager: Click to load display layer set manager. This tool is written to improve the efficiency of building display layers. How...",""],
["distributemgtools_en.htm","Distribute MGTools","If you just want to install MGTools in one single machine, check out the \"Install MGTools\" section at the left. Distributing MGTools for Node-Lock...",""],
["draw_curve_via_key_en.htm","Draw curve via key","Draw curve via keyframe: Draw a nurbs curve via your selection&#39;s keyframe. It could be used to cooperate the motion Path feature. How to call the ...",""],
["edit_fileshortcut_en.htm","Edit File ShortCut","Edit file Shortcut: Click to manage user file shortcut. To edit file shortcut ( Do one of the following ) : Right mouse button click the icon on M...",""],
["edit_foldershortcut_en.htm","Edit folder shortCut","Edit folder Shortcut: Click to manage user folder shortcut. To edit folder shortcut ( Do one of the following ) : Right mouse button click the ico...",""],
["exportimportconstraintoffset_en.htm","Export/Import constraint offset","Export / Import constraint offset information: Click the icons left in the maya shelves to export / import the constraint offset info to / from an...",""],
["feetsnap_en.htm","FootSnap","How to accessing snapping tool ( Do one of the following ) : Click the button of MGTools. Click the icon in your Maya shelves (If U have installed...",""],
["file_shortcut_en.htm","File ShortCut","File/Program shortCut: Click the icon on the MGTools UI to open a certain file / program . All features of this icon have something to do with \"Fi...",""],
["findjointviavertex_en.htm","Find Joint via vertex","Find joint via selected vertex: Select the smooth bind joint via current selected vertex. U can use the joint to constrain object. How to do this ...",""],
["floatinglicence_en.htm","Floating Licence","Node-Locked Licence vs Floating Licence: Node-Locked Licence: Bound to machine, not transferable, need to pay for future brand new features, but t...",""],
["folder_shortcut_en.htm","Folder shortCut","Folder Shortcut: Click the icon on the MGTools UI to open current project folder.Double click to open both project folder and project image folder...",""],
["grapheditor_channel_en.htm","GraphEditor Plugin","GraphEditor channel filter plug-in: Install / remove Ge- plug-in in graphEditor. U can then use them to filter the channels displayed in graphEdit...",""],
["insert_hierarchy_en.htm","InsertHierarchy(2.0new)","Insert Hierarchy: To insert a certain number of hierarchies into current object for keyframing use. The inserted hierarchies will be driven by the...",""],
["install_mgtools_en.htm","Install MGtools","First to MGTools： 1.Visit http://mgland.com to download the latest MGTools .zip release package and extract it to wherever in your local disk . 2....",""],
["keyframeprobe_en.htm","Keyframe Probe","KeyframeProbe Search for keyframed objects of current selected rig. Search result will be listed out to make you know what are moving current rig....",""],
["keyframetool_en.htm","keyframeTools","KeyframeTools: Click to lunch keyframe tools. The tools focus on keyframing things. If you right clicking on button of MGTools, almost each featur...",""],
["make_it_sticky_en.htm","Make Selection Sticky","Stick object to view: Click it to stick the object to current active view. If it is already sticky, then click it to reset it to normal. U gonna u...",""],
["make_sticky_viewport_en.htm","Make Sticky View","Make a sticky view: Create a camera which is constrained to current selection. Not matter how the object move ,in the sticky camera view it will b...",""],
["marker_en.htm","Marker","Marker: Create a locator in the position of the selected object &#39;s pivot. The locator will has frame info of at which it is created. U can select ...",""],
["mb_ma_covertor_en.htm","MB-MA Converter","MB-MA file converter: Click it and follow the prompt windows to convert MB to MA or vise versa by force. Sometime maya don&#39;t allow u to change fil...",""],
["mg-hud_display_en.htm","MG-HUD Display","MG-HeadUpDisplay: HUD display : It will show hud display in your mode panel view via MG HUD config. The Default config is: Show Animator name at t...",""],
["mg-timer_en.htm","MG-Timer","MG-Timer: MG-Timer ,u can use it to record timing in any form: NTSC, PAL, Film, HH:MM:SS ... etc. U can also use it to calc the frames between dif...",""],
["mganimationbank_en.htm","MG-AnimationBank","File/Program shortCut: Click the icon on the MGTools UI to load MG-Animation Library . All features of this icon have something to do with \"File\"....",""],
["mganimrecorder_en.htm","MG_AnimRecorder","Anim-Recorder: Click to load Anim-Recorder tools. This tools record the world/local transformation of objects, you are free to reapply the record ...",""],
["mgautosave_en.htm","MG-Autosave","MG-Autosave: The No.01 pain in ass for animator could be ,after hours of working, the animation just gone after maya crash, windows bluescreen, po...",""],
["mgposeanimlibrary_en.htm","MG-PoseAnimLirbrary","MG-PoseAnim Library: A library tool manages both pose library &#38; animation library. With this tools, it is easy to build, manage and share the pose...",""],
["mgsaver_en.htm","MG-Saver","MB-Saver: This tool is used to speed up your Maya scene saving process. Such as version up, clean up scene before save your scene, etc. Where to f...",""],
["mgsnapshotwidget_en.htm","Snapshot Component","MGTools Generic Snapshot Component: This component is used in MG-PoseAnim Library and MG-AssetLibrary to create preview images and movies. Preview...",""],
["mgtoolintroduction_en.htm","MGtools","MGTools: Click to minimize/Restore MGTools. You can custom the size and position of both minimize mode or normal mode of MGTools. It will automati...",""],
["mgtools_en_ftsearch.htm","MGtools Pro3 Manual","Enter keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): &#169; 2016 MGLAND animation studio You must have JavaScript enabled to use this versio...",""],
["mgtools_menu_en.htm","MGtools Menu","MGTools Menu: To Install MGTools Menu ( Do one of the following ) : Install it when you install MGTools. Install it in MGTools Config UI. After su...",""],
["mgtools_shelf_installer_en.htm","MGtools Installer","To load MGTools Installer ( Do one of the following ) : Click in MGTools Config UI. Right mouse button clicking on the first icon of MGTools and s...",""],
["mg_channelbox_en.htm","MGchannelBox","MGchanelBox: Click the button to load the floating MGchannelBox. MGchannelBox has all the maya default features, and beside that there are some sp...",""],
["mg_selectionset_en.htm","MG_SelectionSet","MG-SelectionSet: Click to load MGselectionSet UI. This button and its pop up menus are mainly selecting features. Special features: Save selection...",""],
["mg_shelfbar_en.htm","MG_shelfBar","MG-Shelf: Click the icon in MGTools to load MG-Shelf bar. MG-Shelf UI: SHF tools button: Similar to MGTools icon in MGTools UI. It is used to mana...",""],
["mg_shelf_en.htm","MG-Shelf","MGShelf: Click it to load MG-Shelf which holds the scripts that U have embed before. Right click on the MGshelf icon: Items above the \"Update This...",""],
["mg_shelf_manager_en.htm","MG_shelf Manager","MG-Shelf Manager: Click it to load MGshelf manager. U can embed/edit your own scripts there. To load MG-Shelf Manager ( Do one of the following ) ...",""],
["minitoolbox_en.htm","MiniToolBox","MiniToolBox : Click to load miniToolBox. Some mini features will be presented here. Features of the right mouse button clicking menu of the button...",""],
["motionpath_en.htm","MotionPath sticker","Motion Path calculator: It will calculate the proper U value of motion path to keep character foot from sliding in minimum when character is movin...",""],
["neworeditselset_en.htm","New/Edit SelectionSet","New / Edit selection set: Convert selection of your scenes to MGselectionSet. New / Edit selection set UI: Section A: The icon image and names of ...",""],
["offlineupdatemgtools_en.htm","Offline Update MGTools","Offline Update MGTools: The feature is deprecated and no longer supported. You always download latest MGTools full program from http://twincodes.c...",""],
["onlineupdatemgtools_en.htm","Online Update MGtools","Online Update MGTools： The feature is deprecated and no longer supported. You always download latest MGTools program from http://twincodes.com and...",""],
["pathtracker_en.htm","PathTracker","Path Tracker: Click to open the path tracker. It is inspired by Spencer Jones&#39; arcTracker, which was introduced by my colleague. Thank you, Spence...",""],
["pivottool_en.htm","PivotTool","Pivot animation tool: Click to load pivot tool. The main feature of this tool is ,it gives animator the ability to animate the selected object&#39;s p...",""],
["pivot_stuff_manager_en.htm","pivot stuff manager","Pivot stuff manager: Load pivot stuff lister to manager the pivot stuffs in your scene. U can easy select / delete pivot stuff there. How to load ...",""],
["poseanim_config_en.htm","Config Library Tool","How to load configuration: Config menu/ configuration.. Project menu/Manage Project.. Library Project Tab: You can create new project, rename proj...",""],
["poseanim_createcharacter.htm","Create Character &#38; Category","How To Create Character: Click the button at the top right of the tool / New Character.. Character menu/New Character.. If current project has not...",""],
["poseanim_createposeanim_en.htm","Create Pose &#38; Anim","Create Pose / Anim Item: Click the icon in the tool. Item Menu / New Item.. Pose Creation Workflow: 1.Select the controllers you want to record po...",""],
["poseanim_createproj_en.htm","Create Library Project","Create A Library Project: Click the button at the top right of the tool / New Project.. Project Menu / New Project.. If no project is available, c...",""],
["poseanim_manageeditlib_en.htm","Edit &#38; Manage Library","Library Editing &#38; Management: Renaming: Rename the Library Project: Need to open up the MG-PoseAnim Library Configuration Window. Select Config/Co...",""],
["poseanim_previewpanel_en.htm","Preview Panel","Preview panel: Click the icon. Double clicking on the item you want to preview. The top row shows the hierarchy of the previewing item, the info i...",""],
["poseanim_sharelib_en.htm","Library Sharing","Workflow of library sharing: 1.The IT manager, make a folder in the server, the folder is only writable to someone who need to manage the global l...",""],
["poseanim_useanim_en.htm","Using Anim Library","Using Animation Library: The apply option panel is at the bottom of the PoseAnim Library UI. Item Clicked: Library Management: The mode is for man...",""],
["poseanim_usepose_en.htm","Using Pose Library","Using Pose Library: The apply option panel is at the bottom of the PoseAnim Library UI. Item Clicked: Library Management: The mode is for managing...",""],
["posnap_en.htm","MG POsnap tool","MG Snap Tools: Click this button to PO snap forward. (Same as parent-constraint with no offset ) This is probably the most popular feature of MGTo...",""],
["reference_tool_en.htm","Reference ToolBox","Reference ToolBox: Source: Decide the tool should get the target reference information from scene selection, or Reference Editor selection. Copy/P...",""],
["registermgtools_en.htm","Register MGTools","Register MGTools: For individual license holder of MGTools Pro, a normal register dialog is preferred. To Register: Right click on the first icon ...",""],
["relative_snap_en.htm","Relative Snap","How to load relative snapping tool: Right mouse button clicking on the button of MGTools and select \"Relative POsnap Forward/Backward\". When to us...",""],
["relocatemgtools_en.htm","MGTools Relocation","If your MGtools Pro was installed in local program mode and now you want to transform it into server program mode, or you wanna transform it from ...",""],
["relocator_en.htm","Relocator","ReLocator: Generate a controller that can relocate multiple objects at the same time. The change will be fitted into the original keyframes. * Thi...",""],
["reset_mgchallbox_channel_en.htm","Reset channelBox channel","Reset selected channels /attributes: Reset selected channels /attributes in channelBox. Selected translation and rotation attributes will be reset...",""],
["scaleanimation_en.htm","Scale Animation","Keyframe scale tool: Scale scene animation. Scale animation to keep animation speed between different frame rates. How to Use: 1.Open UI: 2.Input ...",""],
["scanassetpreviewimage_en.htm","Batch Add PreviewImages","Batch adding preview images: Press the button on MG-Asset Library UI to open this window: Scan and match options: Image formats: The target image ...",""],
["sceneconstraintmanagernode_en.htm","Constraint Manager Node","In-Scene Constraint Manager Node: It is just a normal transform node with a nurbs curve shape. The purpose of the node, is to enable you to collec...",""],
["selection_manager_en.htm","Selection Manager","Selection manager: Temporarily manager your selection. U can do the operations such as sum / subtract / intersect selection. Why using it: Not all...",""],
["selsetshelfconverter_en.htm","SelectionSet Shelf coverter","To convert selection set to Shelf ( Do one of the following ) ： Right mouse button click on button /\"Convert selected/all sets to shelf..\" Right m...",""],
["setkeyframetool_en.htm","SetKeyframe Tool","SetKey Tool: Set key all keyframes or set key per certain frames. In MGTools 2.5, bugs are fixed in this tool. How to use: 1.Open Keyframe tools, ...",""],
["sharingselectionset_en.htm","Selection Set Sharing","How to share SelectionSet: 1.Animation leader build a whole selection set. 2.Animation leader share these .set files, in a server public folder. T...",""],
["shelfconvertor_en.htm","Shelf Convertor","Shelf Convertor Convert shelf files between different Maya version. High maya version tends to add new flags in the shelf file, which makes it una...",""],
["smoothswitch_en.htm","Smooth Switcher","smoothSwitcher： One key switch all polysmooth conditions of your scene. The switcher was made pretty intelligent. If the smooth attribute was cont...",""],
["snapkeyframe_en.htm","Snap Keyframes","Super SnapKeyframe Snap the animation keyframes to integer by force. If time range is selected before snapping, only the keys in the range are sna...",""],
["superundo_en.htm","Efficient Undo/Redo","Efficient Undo/Redo: Click to undo/redo Maya operation. The beauty is that it can step through the null undo/redo and undo/redo many steps by one ...",""],
["tangenttool_en.htm","Tangent Tool","TangentTool: Change tangent type of animCurves. Kind like maya&#39;s tangent type button in GraphEditor. The difference is that you can do this via ti...",""],
["timingtool_en.htm","Timing Tool","Timing Tool: Change the time spacing between previous &#38; next keyframes of currentTime. How to Use: 1.Open Keyframe tools, click on Timing tool tit...",""],
["typeselector_en.htm","typeselector","Type Selector: Filter the scene objects and select them for you. Kind like the \"select by name\" feature of 3dsMax. notice that it only take all DA...",""],
["uninstallmgtools_en.htm","MGTools Uninstaller","To load MGTools Uninstaller ( Do one of the following ) : MGTools Menu/Install/Uninstall/MGTools Uninstaller.. Right click on the MGTools first ic...",""],
["updatefromserver_en.htm","Update MGTools From Server","Update MGTools From Server: If your MGTools was installed in full server program mode, no update from server needed: just restart maya. If you wan...",""],
["uvconstraint_en.htm","UV Constraint","UV Constraint: Make a controller that stick to one point of the model. You hereby can use this controller to constrain any object that you want it...",""],
["vertexconstraint_en.htm","Vertex Constraint","Vertex Constraint: Make a controller that stick to one point of the model. You hereby can use this controller to constrain any object that you wan...",""],
["viewset_en.htm","ViewSet","View switch: Click to switch current active view / all view among the two or three config.The tool was written to improve the efficiency of config...",""],
["welcome_en.htm","Welcome","Welcome to MGTools Pro 3+ ! MGTools is a tool-set made especially for Maya character animators. These tools are designed and tested in production ...",""]];
