AnimCrv: [!!python/unicode 'Brow_ZCon_R_rotateZ', !!python/unicode 'Brow_ZCon_R_translateX',
  !!python/unicode 'BrowCon1_R_rotateZ', !!python/unicode 'BrowCon1_R_translateX',
  !!python/unicode 'BrowCon3_R_rotateZ', !!python/unicode 'BrowCon3_R_translateX',
  !!python/unicode 'BrowCon5_R_rotateZ', !!python/unicode 'BrowCon5_R_translateX',
  !!python/unicode 'cheek_Con_R_rotateY', !!python/unicode 'cheek_Con_R_rotateZ',
  !!python/unicode 'cheek_Con_R_translateZ', !!python/unicode 'Eye_ZCon_R_rotateX',
  !!python/unicode 'Eye_ZCon_R_rotateY', !!python/unicode 'Eye_ZCon_R_translateZ',
  !!python/unicode 'EyeBall_Con_R_rotateY', !!python/unicode 'Eyebrow_ZCon_R_rotateX',
  !!python/unicode 'Eyebrow_ZCon_R_rotateY', !!python/unicode 'Eyebrow_ZCon_R_translateZ',
  !!python/unicode 'EyeDCon12_R_rotateY', !!python/unicode 'EyeDCon12_R_translateZ',
  !!python/unicode 'EyeDCon15_R_rotateY', !!python/unicode 'EyeDCon15_R_translateZ',
  !!python/unicode 'EyeDCon18_R_rotateY', !!python/unicode 'EyeDCon18_R_translateZ',
  !!python/unicode 'EyeDCon3_R_rotateY', !!python/unicode 'EyeDCon3_R_translateZ',
  !!python/unicode 'EyeDCon6_R_rotateY', !!python/unicode 'EyeDCon6_R_translateZ',
  !!python/unicode 'EyeDCon9_R_rotateY', !!python/unicode 'EyeDCon9_R_translateZ',
  !!python/unicode 'Eyedndn_ZCon1_R_translateZ', !!python/unicode 'EyeJnt_Con1_R_rotateX',
  !!python/unicode 'EyeJnt_Con1_R_translateZ', !!python/unicode 'EyeJnt_Con3_R_rotateX',
  !!python/unicode 'EyeJnt_Con3_R_translateZ', !!python/unicode 'EyeJntdn_Con1_R_rotateX',
  !!python/unicode 'EyeJntdn_Con1_R_translateZ', !!python/unicode 'EyeJntdn_Con3_R_rotateX',
  !!python/unicode 'EyeJntdn_Con3_R_translateZ', !!python/unicode 'EyeJntdn_Con5_R_rotateX',
  !!python/unicode 'EyeJntdn_Con5_R_translateZ', !!python/unicode 'EyeJntup_Con1_R_rotateX',
  !!python/unicode 'EyeJntup_Con1_R_translateZ', !!python/unicode 'EyeJntup_Con3_R_rotateX',
  !!python/unicode 'EyeJntup_Con3_R_translateZ', !!python/unicode 'EyeJntup_Con5_R_rotateX',
  !!python/unicode 'EyeJntup_Con5_R_translateZ', !!python/unicode 'Eyeupup_ZCon1_R_translateZ',
  !!python/unicode 'FKScapula_R_translateX', !!python/unicode 'FKScapula_R_translateY',
  !!python/unicode 'FKScapula_R_translateZ', !!python/unicode 'IKArm_R_rotateY', !!python/unicode 'IKArm_R_rotateZ',
  !!python/unicode 'IKArm_R_translateX', !!python/unicode 'IKLeg_R_rotateY', !!python/unicode 'IKLeg_R_rotateZ',
  !!python/unicode 'IKLeg_R_translateX', !!python/unicode 'Mouth_second1_R_Con_translateZ',
  !!python/unicode 'Mouth_second10_Con_translateX', !!python/unicode 'Mouth_second10_Con_translateZ',
  !!python/unicode 'Mouth_second11_Con_translateX', !!python/unicode 'Mouth_second11_Con_translateZ',
  !!python/unicode 'Mouth_second3_R_Con_translateZ', !!python/unicode 'Mouth_second5_Con_translateX',
  !!python/unicode 'Mouth_second5_Con_translateZ', !!python/unicode 'Mouth_second6_Con_translateX',
  !!python/unicode 'Mouth_second6_Con_translateZ', !!python/unicode 'Mouth_second7_Con_translateX',
  !!python/unicode 'Mouth_second7_Con_translateZ', !!python/unicode 'Mouth_second8_Con_translateX',
  !!python/unicode 'Mouth_second8_Con_translateZ', !!python/unicode 'Mouth_second9_Con_translateX',
  !!python/unicode 'Mouth_second9_Con_translateZ', !!python/unicode 'Mouth1_Con_rotateX',
  !!python/unicode 'Mouth1_Con_translateZ', !!python/unicode 'Mouth11_Con_translateZ',
  !!python/unicode 'Mouth5_Con_translateZ', !!python/unicode 'naso_01_Con_R_rotateX',
  !!python/unicode 'naso_01_Con_R_rotateY', !!python/unicode 'naso_01_Con_R_translateZ',
  !!python/unicode 'naso_02_Con_R_rotateX', !!python/unicode 'naso_02_Con_R_rotateY',
  !!python/unicode 'naso_02_Con_R_translateZ', !!python/unicode 'naso_03_Con_R_rotateX',
  !!python/unicode 'naso_03_Con_R_rotateY', !!python/unicode 'naso_03_Con_R_translateZ',
  !!python/unicode 'naso_Con_R_rotateX', !!python/unicode 'naso_Con_R_rotateY', !!python/unicode 'naso_Con_R_translateZ',
  !!python/unicode 'nose_Con_R_rotateX', !!python/unicode 'nose_Con_R_rotateY', !!python/unicode 'nose_Con_R_translateZ',
  !!python/unicode 'PoleArm_R_translateX', !!python/unicode 'PoleLeg_R_translateX',
  !!python/unicode 'R_Brow_00_Sec_Con_rotateX', !!python/unicode 'R_Brow_00_Sec_Con_rotateY',
  !!python/unicode 'R_Brow_00_Sec_Con_translateZ', !!python/unicode 'R_Brow_01_Sec_Con_rotateX',
  !!python/unicode 'R_Brow_01_Sec_Con_rotateY', !!python/unicode 'R_Brow_01_Sec_Con_translateZ',
  !!python/unicode 'R_Brow_02_Sec_Con_rotateX', !!python/unicode 'R_Brow_02_Sec_Con_rotateY',
  !!python/unicode 'R_Brow_02_Sec_Con_translateZ', !!python/unicode 'R_Brow_03_Sec_Con_rotateX',
  !!python/unicode 'R_Brow_03_Sec_Con_rotateY', !!python/unicode 'R_Brow_03_Sec_Con_translateZ',
  !!python/unicode 'R_Brow_04_Sec_Con_rotateX', !!python/unicode 'R_Brow_04_Sec_Con_rotateY',
  !!python/unicode 'R_Brow_04_Sec_Con_translateZ', !!python/unicode 'R_Cheek_00_Sec_Con_rotateX',
  !!python/unicode 'R_Cheek_00_Sec_Con_rotateY', !!python/unicode 'R_Cheek_00_Sec_Con_translateZ',
  !!python/unicode 'R_Cheek_Con_rotateX', !!python/unicode 'R_Cheek_Con_rotateY',
  !!python/unicode 'R_Cheek_Con_translateZ', !!python/unicode 'R_CheekIn_01_Sec_Con_rotateX',
  !!python/unicode 'R_CheekIn_01_Sec_Con_rotateY', !!python/unicode 'R_CheekIn_01_Sec_Con_translateZ',
  !!python/unicode 'R_EyeLideLattice_inner_Con_translateX', !!python/unicode 'R_EyeLideLattice_lower_Con_translateX',
  !!python/unicode 'R_EyeLideLattice_outer_Con_translateX', !!python/unicode 'R_EyeLideLattice_upper_Con_translateX',
  !!python/unicode 'R_EyeLidSec_00_Con_rotateX', !!python/unicode 'R_EyeLidSec_00_Con_rotateY',
  !!python/unicode 'R_EyeLidSec_00_Con_translateZ', !!python/unicode 'R_EyeLidSec_01_Con_rotateX',
  !!python/unicode 'R_EyeLidSec_01_Con_rotateY', !!python/unicode 'R_EyeLidSec_01_Con_translateZ',
  !!python/unicode 'R_EyeLidSec_02_Con_rotateX', !!python/unicode 'R_EyeLidSec_02_Con_rotateY',
  !!python/unicode 'R_EyeLidSec_02_Con_translateZ', !!python/unicode 'R_EyeLidSec_03_Con_rotateX',
  !!python/unicode 'R_EyeLidSec_03_Con_rotateY', !!python/unicode 'R_EyeLidSec_03_Con_translateZ',
  !!python/unicode 'R_EyeLidSec_04_Con_rotateX', !!python/unicode 'R_EyeLidSec_04_Con_rotateY',
  !!python/unicode 'R_EyeLidSec_04_Con_translateZ', !!python/unicode 'R_EyeLidSec_05_Con_rotateX',
  !!python/unicode 'R_EyeLidSec_05_Con_rotateY', !!python/unicode 'R_EyeLidSec_05_Con_translateZ',
  !!python/unicode 'R_EyeSec_02_Con_rotateX', !!python/unicode 'R_EyeSec_02_Con_rotateY',
  !!python/unicode 'R_EyeSec_02_Con_translateZ', !!python/unicode 'R_EyeSec_03_Con_rotateX',
  !!python/unicode 'R_EyeSec_03_Con_rotateY', !!python/unicode 'R_EyeSec_03_Con_translateZ',
  !!python/unicode 'R_EyeSec_04_Con_rotateX', !!python/unicode 'R_EyeSec_04_Con_rotateY',
  !!python/unicode 'R_EyeSec_04_Con_translateZ', !!python/unicode 'R_EyeSec_06_Con_rotateX',
  !!python/unicode 'R_EyeSec_06_Con_rotateY', !!python/unicode 'R_EyeSec_06_Con_translateZ',
  !!python/unicode 'R_EyeSec_07_Con_rotateX', !!python/unicode 'R_EyeSec_07_Con_rotateY',
  !!python/unicode 'R_EyeSec_07_Con_translateZ', !!python/unicode 'R_EyeSec_08_Con_rotateX',
  !!python/unicode 'R_EyeSec_08_Con_rotateY', !!python/unicode 'R_EyeSec_08_Con_translateZ',
  !!python/unicode 'R_headLowerLattice_Con_translateZ', !!python/unicode 'R_headUpperLattice_Con_translateZ',
  !!python/unicode 'R_JawLine_00_Sec_Con_rotateX', !!python/unicode 'R_JawLine_00_Sec_Con_rotateY',
  !!python/unicode 'R_JawLine_00_Sec_Con_translateZ', !!python/unicode 'R_JawLine_01_Sec_Con_rotateX',
  !!python/unicode 'R_JawLine_01_Sec_Con_rotateY', !!python/unicode 'R_JawLine_01_Sec_Con_translateZ',
  !!python/unicode 'R_JawLine_02_Sec_Con_rotateX', !!python/unicode 'R_JawLine_02_Sec_Con_rotateY',
  !!python/unicode 'R_JawLine_02_Sec_Con_translateZ', !!python/unicode 'R_MouthConner_00_Sec_Con_rotateX',
  !!python/unicode 'R_MouthConner_00_Sec_Con_rotateY', !!python/unicode 'R_MouthConner_00_Sec_Con_translateZ',
  !!python/unicode 'R_MouthLower_00_Sec_Con_rotateX', !!python/unicode 'R_MouthLower_00_Sec_Con_rotateY',
  !!python/unicode 'R_MouthLower_00_Sec_Con_translateZ', !!python/unicode 'R_MouthLower_01_Sec_Con_rotateX',
  !!python/unicode 'R_MouthLower_01_Sec_Con_rotateY', !!python/unicode 'R_MouthLower_01_Sec_Con_translateZ',
  !!python/unicode 'R_MouthUpper_00_Sec_Con_rotateX', !!python/unicode 'R_MouthUpper_00_Sec_Con_rotateY',
  !!python/unicode 'R_MouthUpper_00_Sec_Con_translateZ', !!python/unicode 'R_MouthUpper_01_Sec_Con_rotateX',
  !!python/unicode 'R_MouthUpper_01_Sec_Con_rotateY', !!python/unicode 'R_MouthUpper_01_Sec_Con_translateZ',
  !!python/unicode 'R_NoseMouth_Con_rotateX', !!python/unicode 'R_NoseMouth_Con_rotateY',
  !!python/unicode 'R_NoseMouth_Con_translateZ', !!python/unicode 'R_NoseMouth_Upper_Con_rotateX',
  !!python/unicode 'R_NoseMouth_Upper_Con_rotateY', !!python/unicode 'R_NoseMouth_Upper_Con_translateZ',
  !!python/unicode 'R_Orbit_00_Sec_Con_rotateX', !!python/unicode 'R_Orbit_00_Sec_Con_rotateY',
  !!python/unicode 'R_Orbit_00_Sec_Con_translateZ', !!python/unicode 'R_Orbit_01_Sec_Con_rotateX',
  !!python/unicode 'R_Orbit_01_Sec_Con_rotateY', !!python/unicode 'R_Orbit_01_Sec_Con_translateZ',
  !!python/unicode 'R_Orbit_02_Sec_Con_rotateX', !!python/unicode 'R_Orbit_02_Sec_Con_rotateY',
  !!python/unicode 'R_Orbit_02_Sec_Con_translateZ', !!python/unicode 'R_Orbit_03_Sec_Con_rotateX',
  !!python/unicode 'R_Orbit_03_Sec_Con_rotateY', !!python/unicode 'R_Orbit_03_Sec_Con_translateZ',
  !!python/unicode 'R_OribitAdd_00_Part_Con_rotateX', !!python/unicode 'R_OribitAdd_00_Part_Con_rotateY',
  !!python/unicode 'R_OribitAdd_00_Part_Con_translateZ', !!python/unicode 'R_OribitAdd_00_Sec_Con_rotateX',
  !!python/unicode 'R_OribitAdd_00_Sec_Con_rotateY', !!python/unicode 'R_OribitAdd_00_Sec_Con_translateZ',
  !!python/unicode 'R_OribitAdd_01_Sec_Con_rotateX', !!python/unicode 'R_OribitAdd_01_Sec_Con_rotateY',
  !!python/unicode 'R_OribitAdd_01_Sec_Con_translateZ', !!python/unicode 'R_OribitAdd_02_Part_Con_rotateX',
  !!python/unicode 'R_OribitAdd_02_Part_Con_rotateY', !!python/unicode 'R_OribitAdd_02_Part_Con_translateZ',
  !!python/unicode 'R_OribitAdd_02_Sec_Con_rotateX', !!python/unicode 'R_OribitAdd_02_Sec_Con_rotateY',
  !!python/unicode 'R_OribitAdd_02_Sec_Con_translateZ', !!python/unicode 'R_OribitAdd_03_Sec_Con_rotateX',
  !!python/unicode 'R_OribitAdd_03_Sec_Con_rotateY', !!python/unicode 'R_OribitAdd_03_Sec_Con_translateZ',
  !!python/unicode 'R_OribitAdd_04_Part_Con_rotateX', !!python/unicode 'R_OribitAdd_04_Part_Con_rotateY',
  !!python/unicode 'R_OribitAdd_04_Part_Con_translateZ', !!python/unicode 'R_OribitAdd_04_Sec_Con_rotateX',
  !!python/unicode 'R_OribitAdd_04_Sec_Con_rotateY', !!python/unicode 'R_OribitAdd_04_Sec_Con_translateZ',
  !!python/unicode 'R_SecInner_01_Con_rotateX', !!python/unicode 'R_SecInner_01_Con_rotateY',
  !!python/unicode 'R_SecInner_01_Con_translateZ', !!python/unicode 'R_SecInner_02_Con_rotateX',
  !!python/unicode 'R_SecInner_02_Con_rotateY', !!python/unicode 'R_SecInner_02_Con_translateZ',
  !!python/unicode 'R_SecInner_03_Con_rotateX', !!python/unicode 'R_SecInner_03_Con_rotateY',
  !!python/unicode 'R_SecInner_03_Con_translateZ', !!python/unicode 'R_SecInner_04_Con_rotateX',
  !!python/unicode 'R_SecInner_04_Con_rotateY', !!python/unicode 'R_SecInner_04_Con_translateZ',
  !!python/unicode 'R_SecOuter_01_Con_rotateX', !!python/unicode 'R_SecOuter_01_Con_rotateY',
  !!python/unicode 'R_SecOuter_01_Con_translateZ', !!python/unicode 'R_SecOuter_02_Con_rotateX',
  !!python/unicode 'R_SecOuter_02_Con_rotateY', !!python/unicode 'R_SecOuter_02_Con_translateZ',
  !!python/unicode 'R_SecOuter_03_Con_rotateX', !!python/unicode 'R_SecOuter_03_Con_rotateY',
  !!python/unicode 'R_SecOuter_03_Con_translateZ', !!python/unicode 'R_SecOuter_04_Con_rotateX',
  !!python/unicode 'R_SecOuter_04_Con_rotateY', !!python/unicode 'R_SecOuter_04_Con_translateZ',
  !!python/unicode 'R_SecOuter_05_Con_rotateX', !!python/unicode 'R_SecOuter_05_Con_rotateY',
  !!python/unicode 'R_SecOuter_05_Con_translateZ', !!python/unicode 'R_SmileLines_01_Part_Con_rotateX',
  !!python/unicode 'R_SmileLines_01_Part_Con_rotateY', !!python/unicode 'R_SmileLines_01_Part_Con_translateZ',
  !!python/unicode 'R_SmileLines_01_Sec_Con_rotateX', !!python/unicode 'R_SmileLines_01_Sec_Con_rotateY',
  !!python/unicode 'R_SmileLines_01_Sec_Con_translateZ', !!python/unicode 'R_SmileLines_02_Sec_Con_rotateX',
  !!python/unicode 'R_SmileLines_02_Sec_Con_rotateY', !!python/unicode 'R_SmileLines_02_Sec_Con_translateZ',
  !!python/unicode 'R_SmileLines_03_Part_Con_rotateX', !!python/unicode 'R_SmileLines_03_Part_Con_rotateY',
  !!python/unicode 'R_SmileLines_03_Part_Con_translateZ', !!python/unicode 'R_SmileLines_03_Sec_Con_rotateX',
  !!python/unicode 'R_SmileLines_03_Sec_Con_rotateY', !!python/unicode 'R_SmileLines_03_Sec_Con_translateZ',
  !!python/unicode 'R_SmileLines_04_Sec_Con_rotateX', !!python/unicode 'R_SmileLines_04_Sec_Con_rotateY',
  !!python/unicode 'R_SmileLines_04_Sec_Con_translateZ', !!python/unicode 'R_SmileLines_05_Part_Con_rotateX',
  !!python/unicode 'R_SmileLines_05_Part_Con_rotateY', !!python/unicode 'R_SmileLines_05_Part_Con_translateZ',
  !!python/unicode 'R_SmileLines_05_Sec_Con_rotateX', !!python/unicode 'R_SmileLines_05_Sec_Con_rotateY',
  !!python/unicode 'R_SmileLines_05_Sec_Con_translateZ', !!python/unicode 'R_SmileLines_Big_01_Con_rotateX',
  !!python/unicode 'R_SmileLines_Big_01_Con_rotateY', !!python/unicode 'R_SmileLines_Big_01_Con_translateZ',
  !!python/unicode 'R_SmileLines_Big_02_Con_rotateX', !!python/unicode 'R_SmileLines_Big_02_Con_rotateY',
  !!python/unicode 'R_SmileLines_Big_02_Con_translateZ', !!python/unicode 'R_SocketInner_00_Part_Sec_Con_translateZ',
  !!python/unicode 'R_SocketLower_00_Part_Sec_Con_translateZ', !!python/unicode 'R_SocketLower_01_Part_Sec_Con_translateZ',
  !!python/unicode 'R_SocketLower_02_Part_Sec_Con_translateZ', !!python/unicode 'R_SocketOuter_00_Part_Sec_Con_translateZ',
  !!python/unicode 'R_SocketUpper_00_Part_Sec_Con_translateZ', !!python/unicode 'R_SocketUpper_01_Part_Sec_Con_translateZ',
  !!python/unicode 'R_SocketUpper_02_Part_Sec_Con_translateZ', !!python/unicode 'R_Squint_00_Con_rotateX',
  !!python/unicode 'R_Squint_00_Con_rotateY', !!python/unicode 'R_Squint_00_Con_translateZ',
  !!python/unicode 'R_Squint_01_Con_rotateX', !!python/unicode 'R_Squint_01_Con_rotateY',
  !!python/unicode 'R_Squint_01_Con_translateZ', !!python/unicode 'R_Squint_02_Con_rotateX',
  !!python/unicode 'R_Squint_02_Con_rotateY', !!python/unicode 'R_Squint_02_Con_translateZ',
  !!python/unicode 'R_Squint_03_Con_rotateX', !!python/unicode 'R_Squint_03_Con_rotateY',
  !!python/unicode 'R_Squint_03_Con_translateZ', !!python/unicode 'R_Squint_04_Con_rotateX',
  !!python/unicode 'R_Squint_04_Con_rotateY', !!python/unicode 'R_Squint_04_Con_translateZ',
  !!python/unicode 'RollHeel_R_rotateY', !!python/unicode 'RollHeel_R_rotateZ', !!python/unicode 'RollHeel_R_translateX',
  !!python/unicode 'RollLongToe4_R_rotateY', !!python/unicode 'RollLongToe4_R_rotateZ',
  !!python/unicode 'RollLongToe4_R_translateX', !!python/unicode 'RollToes_R_rotateY',
  !!python/unicode 'RollToes_R_rotateZ', !!python/unicode 'RollToes_R_translateX',
  !!python/unicode 'squintCon_R_rotateY', !!python/unicode 'squintCon_R_rotateZ',
  !!python/unicode 'squintCon_R_translateX']
