pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["animator.htm","动画师帮助","MG-Picker工作室的动画师模式: 动画师模式的界面采用极简设计，以便节省动画师的工作空间。 这个模式下的功能，主要集中在Picker的搜索及加载，及Picker的用户交互。 注意，在动画师模式下，所有的Picker编辑不可保存，你必须按F8切到设计师模式下才能保存。 在动画师模式下，所...",""],
["animatorinteractivity.htm","Picker交互","动画师Picker交互: MG-Picker提供强大丰富的动画师Picker交互方式。 确保您当前处于动画师交互方式，这意味着界面这个按钮被选中： - 选择: 采用跟Maya类似的选择规则. 鼠标左键点击选择按钮/框选它们：选择相应的节点。 CTRL + 鼠标左键点击选择按钮/框选它们：去选...",""],
["codesnippets.htm","代码片段","代码片段是一些用来提升命令编写效率的脚本。 在属性编辑器的代码编辑器，比如说一个命令按钮的命令编辑区，或菜单编辑器下方的代码编辑器， 在这些编辑器右上方都有一个箭号按钮，点击则显示针对当前代码语言类型的所有代码片段，如当前语言是mel则只显示mel的代码片段，是python则只显示pytho...",""],
["commandbuttonpresets.htm","命令按钮预设","命令按钮预设是一些用来提升命令按钮创建效率的脚本。 这些预设脚本使您将来在不用再做任何编程的情况下，创建命令按钮。 在设计模式下，确保编辑工具 或命令按钮工具 处于被激活状态，右键点击picker视图，选择添加命令按钮菜单， 这个菜单列出了所有的命令按钮预设，选择一项来在之前鼠标点击位置创建...",""],
["converters.htm","转换器","转换器是用来将其它类型的picker节点、文件转换成mgpicker节点或文件的mel脚本。 转换器非常多地使用了由MG-Picker工作室提供的MEL API命令，主要是这三个命令： MGPicker , MGPickerItem , MGPickerLink . 请参考这些命令的文档来了...",""],
["customeloaderandlister.htm","Loader和Lister","如果您需要: - 选择场景Rig任意部分，然后MG-Picker工作室有办法加载相对应的picker并设置好namespace. - 无需选择，点击右上角 \"...\" 按钮访问更多功能菜单，在里面的&#8220;加载所有Picker&#8221; 菜单里，点击任意一个菜单项，来加载全部的picker。 - 所有这些...",""],
["designer.htm","设计师帮助","MG-Picker工作室设计师模式: MG-Picker工作室的设计师模式看起来\"复杂\"，因为界面上有那么多的按钮输入框等。但实际上使用起来很简单。 - 基本使用流程: 1.在第1区切换需要的工具; 2.在第2区创建，编辑Picker对象; 3.在第3区的属性编辑器里编辑设置Picker对象...",""],
["designprinciple.htm","设计原则","Picker的设计原则: 事实上没有所谓的picker规则，您可以自由发挥想象力，设计出酷弦又实用的picker。 不过如果您可以在设计时注意下面几点，那么设计出来的picker可能会比较好用并且动画师友好。 一个Picker代表一个资产，这个资产可能是角色，道具或场景等。然后在该Picke...",""],
["distributeinpipeline.htm","在线上分发Picker","MG-Picker工具搜索3个基本路径及其它多个自定义路径来取得匹配的picker: 直接保存在Maya场景内部. Picker数据可以以节点方式存储在maya场景内部。这个节点采用maya内置节点类型 \"subdivSurfaceVarGroup\"; picker节点所用到的图片，一般存储...",""],
["editing.htm","编辑","基本上，你将使用编辑工具 ，变形工具 ，复制粘贴属性工具 来进行移动，编辑操作。 变形所选对象 你可以用编辑工具来移动picker对象，在属性编辑器里设置它们的大小。 不过除此外，你可以使用\"CTRL + T\"快捷键来切到变形工具 来变形事先选择的多个按钮以便整体位移，缩放它们。 变形后，用...",""],
["hotkeys_anim.htm","快捷键","要在动画师模式下使用picker快捷键: 从MG-Picker工作室 v1.6版本及以后，动画师模式下的picker快捷键被缩减至最少。 大部分情况下，快捷键将作用于maya，即你用的是maya快捷键， 如果想使用picker的快捷键，你必须确保当前激活的是picker窗口，然后同时鼠标在p...",""],
["hotkeys_designer.htm","快捷键","要在设计师模式下使用picker快捷键: 只要当前激活的是picker窗口，在设计师模式下你用的都是picker快捷键。 要查看在设计师模式下都有哪些快捷键可用？ 点击&#8220;帮助&#8221;菜单，选择&#8220;快捷键总览&#8221;。 这个功能实际上基于一个picker文件：） ",""],
["install.htm","安装MG-Picker工作室","第一次安装MG-Picker工作室： 1.访问 http://twincodes.com 或 http://mgland.com 下载最新的MG-Picker工作室程序并解压到您的本地硬盘。 2.不要变更里面的任何文件/文件夹，用鼠标左键拖拽\"MGPicker_installer.mel\"到...",""],
["itemshapes.htm","Picker形状","对象形状: 一个picker对象，比如一个选择按钮，命令按钮，滑条，属性按钮，文本，面板等，它们都肯定包含一个形状。 这些形状负责绘制这个picker对象的外观，目前形状有下面多种类型，以便您可以让您的picker按钮尽量像原始的控制器： 矩形， 圆角矩形， 椭圆，圆形， 钻石， 梯形，五边...",""],
["itemtypes.htm","Picker类型","目前有6种Picker对象类型: 选择按钮: 选择按钮用于maya选择，每个选择按钮都有一个maya节点成员列表。 你可以为选择按钮指定一个后续动作，以便这个按钮被点击后，maya自动切到位移/旋转/缩放工具以便动画师继续调整。 并且每次点击或框选选择按钮后，会自动把焦点放在maya的3D视...",""],
["links.htm","Picker连接","目前有2种picker连接: - 父子连接: 父子连接只能用于选择按钮，或滑条的滑杠（实际上也是选择按钮）。 选择连接工具 ， 在选择按钮上点击，然后拖动将它连到另一个选择按钮。一个父子连接就被创建了。 如果要同时将多个选择按钮连到一个选择按钮上，只需要先选择这些源选择按钮，然后点击其中一个...",""],
["loadpicker.htm","加载Pickers","多个加载相关Picker的方法: 1.默认情况下，所有场景内的Picker节点在读取maya档案后将会被自动加载。 这个自动加载与否的选项可以通过选择更多功能按钮 /配置..，在弹出的配置对话框里设置。 2.选择Reference角色的任意一部分， ALT+鼠标左键双击Picker标签的空白...",""],
["mg-picker_simplifiedchinese_ftsearch.htm","MG-Picker工作室帮助","Enter keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): &#169; 2017 MGLAND动画工作室 You must have JavaScript enabled to use this version of the sea...",""],
["mgimageprocesser.htm","MGImageProcesser Command","命令 (MEL/Python) MGImageProcesser 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGImageProcesser [- dimension ] [- processOption ] [-...",""],
["mgpicker.htm","MGPicker Command","命令 (MEL/Python) MGPicker 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGPicker [- about ] [- aboutCurrentPicker ] [- activate ] [- ...",""],
["mgpickeritem.htm","MGPickerItem Command","命令 (MEL/Python) MGPickerItem 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGPickerItem [- applyMirroredAttribute ] [- annotation ] ...",""],
["mgpickerlink.htm","MGPickerLink Command","命令 (MEL/Python) MGPickerLink 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGPickerLink [- exist ] [- remove ] [- source ] [- target...",""],
["mgpickermenu.htm","MGPickerMenu Command","命令 (MEL/Python) MGPickerMenu 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGPickerMenu [- addMenuItem ] [- copyMenu ] [- copyPaired...",""],
["mgpickermenuitem.htm","MGPickerMenuItem Command","命令 (MEL/Python) MGPickerMenuItem 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGPickerMenuItemItem [- addSubMenuItem ] [- command ]...",""],
["mgpickerservice.htm","MGPickerService Command","命令 (MEL/Python) MGPickerService 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGPickerService [- cleanNamespaceMix ] [- getViewCoord...",""],
["mgpickerview.htm","MGPickerView Command","命令 (MEL/Python) MGPickerView 跳转到: MEL概要 . Python概要 . 返回值 . 标签 . MEL例子 . Python例子 . MEL概要 MGPickerView [- activate ] [- addPanel ] [- activePanelIn...",""],
["mgselecthelper.htm","MG-选择辅助器","MG-选择辅助器: 它是用来存储暂时选择的地方，辅助您的选择。 你可以同时打开无限制个数的选择辅助器实例。 两种方式打开选择辅助器： 1.鼠标左键点击右上角更多功能按钮 并选择\"新选择辅助窗口\"。 2.CTRL / SHIFT 鼠标右键一个选择按钮，会弹出成员视图，点击其右上的按钮把它变成选...",""],
["more_resource.htm","更多资源","针对流行maya rig的免费picker下载： http://mgland.com/MGPicker_ch.html?url=Download 视频教程： http://mgland.com/MGPicker_ch.html?url=Features ",""],
["namespace.htm","Namespace","设置当前picker的namespace： Namespace是当前Picker的命令空间，即前缀名。改变这个前缀名，使你可以将Picker在所有其它命名类似的角色上使用。 -在设计师模式下设置namespace的两种方式: 1.选择reference角色的任一部分，按Ctrl+Alt+Sh...",""],
["pickermenu.htm","Picker菜单","每个picker对象都可以内置一个左键或右键菜单 。 - 要为picker对象设置左、右键菜单: 选择picker对象，来到菜单编辑器。 创建、编辑菜单的基本流程如下图： 你可以按\"Ctrl+C\", \"Ctrl+X\", \"Ctrl+V\" 来复制剪切粘贴菜单项。 你可以拖放图中的菜单项到不同的...",""],
["pickertoolintergration.htm","整合Picker工具","关于MG-Picker工作室版本控制的建议: 为什么需要版本控制: 大公司往往有自己的软件包的打包及管理系统，及版本管理系统。他们需要在这些系统里作一些设置，以使用更新的Picker工具，或回卷使用旧的工具版本。 面临的问题: 目前在maya 2017+的版本， MG-Picker工作室使用...",""],
["programmer.htm","程序员帮助","MG-Picker工作室尽全力让您设计强大的picker，在不用敲任何代码的情况下。 不过如果您有一些mel / python脚本开发经验，那么您设计的picker可以变得更加强大。 以下就一些您可以发挥脚本开发能力的地方： - Picker里可编程的属性. 所有这些属性都支持mel或pyt...",""],
["publishinternet.htm","发布到网络","如果您是一个绑定师，正想要将您的角色及其picker发布到网络上： 选择Picker菜单 / 发布当前Picker.. Picker发布对话框将弹出。 您可以选择发布您当前的maya场景，发布picker为文件或节点，甚至可以附上整个MG-Picker工作室程序，然后整个将上面数据打包成zi...",""],
["quickworkflow.htm","快速流程","Picker设置快速流程: - 创建流程 #1: 从已制作好的Picker模板来新建Picker: -3种方式从Picker模板新建Picker: 1. ALT+左键双击Picker文件标签区空白处，如果当前没有打开任何Picker，也可以同样方式Picker视图区。 2.使用 \"CTRL ...",""],
["q__a.htm","Q &#38; A","Q: 如何避免硬写picker对象的id? 要获取当前正编辑或互动的picker对象的id, 比如你在编写一个命令按钮的命令，要获取这个命令按钮的id （下面是mel代码，python方式类似）： string $currentCmdBtn = `MGPicker -q -currentIt...",""],
["setnamespace.htm","设置Namespace","设置当前picker的namespace： Namespace是当前Picker的命令空间，即前缀名。改变这个前缀名，使你可以将Picker在所有其它命名类似的角色上使用。 -设置namespace的两种方式: 1.选择reference角色的任一部分，按Ctrl+Alt+Shift+S快捷...",""],
["simpleediting.htm","简单编辑","动画师模式下的简单创建&#38;编辑功能: 在使用Picker时如果创建一些暂用的Picker按钮，您可以按\"W\"快捷键来切到简单编辑工具，再按一次\"Q\"则是返回动画师交互模式，按\"Y\"来在两者间切换。 在该模式下，你可以选择，移动Picker对象并用上图的两个颜色按钮给他们指定填充色及标签色。 的...",""],
["syncvaluewithmaya.htm","跟Maya同步","对于控制着maya属性的属性按钮及滑条 来讲： 这种picker对象会自动随maya属性变更而更新，所以无需写任何代码。 只有少部分情况下两者不会同步： 在picker加载后才创建的maya节点， 或者在picker加载后才load进来的reference。 对于这些情况，你只需要将你的鼠标...",""],
["tipsforanimator.htm","小提示","MG-Picker工作室动画师模式小提示: 使用 \"Ctrl+F\" 及 \"Esc\" 快捷键来在显示/隐藏属性搜索界面。 你可以直接在动画师模式下使用maya快捷键。在设计师模式下，则只能使用picker的快捷键，无法使用maya的。 在你使用选择按钮或滑条滑杠影响了maya选择后，工具会自动...",""],
["tipsfordesigner.htm","小提示","MG-Picker工作室在设计师模式下的小技巧: 每一个菜单项，界面按钮，属性控件都有鼠标经过提示，可以阅读这些提示来了解它的用途。 当您为picker截图生成图片时，比如为面板生成背景图片，你可以应用一个自动化的图片处理预设。这个预设在截图产生后自动被应用，像photoshop的滤镜。 如...",""],
["tipsforprogrammer.htm","小提示","MG-Picker工作室编程及picker开发的小提示: 频繁被使用的命令做成直观访问的命令按钮，并把它放在picker面板里。 对于视图操作，比如自动放大显示某一picker面板这种，你可以把切换面板的命令做到所有面板的右键marking menu菜单里。 这意味着，你选择所有的picke...",""],
["viewportmanipulation.htm","视图操作","Picker视图操作: -MG-Picker视图操作采用跟Maya的3D视图相似的操作规则: 鼠标中键: 平移视图，不管有没有按ALT键。 ALT + 鼠标右键: 放大/缩小视图。 CTRL + ALT + 鼠标左键: 框选的方式放大局部/重置到默认大小。 F 键: 放大选中的Picker对...",""],
["welcome.htm","欢迎","欢迎使用MG-Picker工作室 ! MG-Picker工作室是一个能让您甚至在没有编写任何代码情况下，创建及使用强大的，丰富的对动画师友好的Picker界面的Maya插件。 主功能清单 : 1.不懂编程就能设计强大的动画师友好的picker界面。 2.丰富的动画师picker交互方式。场景...",""]];
