# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\OCT_Toolkits\DCC_TOOLS\common\Loader\oct_loader_ui.ui',
# licensing of 'D:\OCT_Toolkits\DCC_TOOLS\common\Loader\oct_loader_ui.ui' applies.
#
# Created: Fri Dec  6 15:40:52 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
import my_list_widget

class Ui_MainWindow_OCT_Loader_UI(object):
    def setupUi(self, MainWindow_OCT_Loader_UI):
        MainWindow_OCT_Loader_UI.setObjectName("MainWindow_OCT_Loader_UI")
        MainWindow_OCT_Loader_UI.resize(1093, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow_OCT_Loader_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_title = QtWidgets.QHBoxLayout()
        self.horizontalLayout_title.setObjectName("horizontalLayout_title")
        self.label_icon = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon.sizePolicy().hasHeightForWidth())
        self.label_icon.setSizePolicy(sizePolicy)
        self.label_icon.setMinimumSize(QtCore.QSize(36, 36))
        self.label_icon.setStyleSheet("color: rgb(255, 187, 49);\n"
"background-color: rgb(170, 170, 255);")
        self.label_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icon.setObjectName("label_icon")
        self.horizontalLayout_title.addWidget(self.label_icon)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_title.addWidget(self.label_title)
        self.gridLayout_4.addLayout(self.horizontalLayout_title, 0, 0, 1, 3)
        self.groupBox_left = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_left.sizePolicy().hasHeightForWidth())
        self.groupBox_left.setSizePolicy(sizePolicy)
        self.groupBox_left.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_left.setTitle("")
        self.groupBox_left.setObjectName("groupBox_left")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_left)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_left)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_project = QtWidgets.QWidget()
        self.tab_project.setObjectName("tab_project")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_project)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget_project = QtWidgets.QTreeWidget(self.tab_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.treeWidget_project.setFont(font)
        self.treeWidget_project.setObjectName("treeWidget_project")
        self.treeWidget_project.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidget_project, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_project, "")
        self.tab_task = QtWidgets.QWidget()
        self.tab_task.setObjectName("tab_task")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_task)
        self.gridLayout_5.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeWidget_task = QtWidgets.QTreeWidget(self.tab_task)
        self.treeWidget_task.setObjectName("treeWidget_task")
        self.treeWidget_task.header().setVisible(False)
        self.gridLayout_5.addWidget(self.treeWidget_task, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_task, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_left, 1, 0, 1, 1)
        self.groupBox_middle = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_middle.setTitle("")
        self.groupBox_middle.setObjectName("groupBox_middle")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_middle)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_scale = QtWidgets.QFrame(self.groupBox_middle)
        self.frame_scale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_scale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_scale.setLineWidth(0)
        self.frame_scale.setObjectName("frame_scale")
        self.gridLayout_scale = QtWidgets.QGridLayout(self.frame_scale)
        self.gridLayout_scale.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_scale.setSpacing(0)
        self.gridLayout_scale.setObjectName("gridLayout_scale")
        spacerItem = QtWidgets.QSpacerItem(244, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_scale.addItem(spacerItem, 0, 0, 1, 1)
        self.label_scale_min = QtWidgets.QLabel(self.frame_scale)
        self.label_scale_min.setEnabled(True)
        self.label_scale_min.setObjectName("label_scale_min")
        self.gridLayout_scale.addWidget(self.label_scale_min, 0, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_scale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimum(66)
        self.horizontalSlider.setMaximum(188)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_scale.addWidget(self.horizontalSlider, 0, 2, 1, 1)
        self.label_scale_max = QtWidgets.QLabel(self.frame_scale)
        self.label_scale_max.setEnabled(True)
        self.label_scale_max.setObjectName("label_scale_max")
        self.gridLayout_scale.addWidget(self.label_scale_max, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.frame_scale, 2, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_middle)
        # self.listWidget = my_list_widget.MenuListWidget()
        # print dir(self.listWidget)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget.setIconSize(QtCore.QSize(100, 100))
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 1, 0, 1, 1)
        self.horizontalLayout_m_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_m_top.setSpacing(2)
        self.horizontalLayout_m_top.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_m_top.setObjectName("horizontalLayout_m_top")
        self.lineEdit_find = QtWidgets.QLineEdit(self.groupBox_middle)
        self.lineEdit_find.setObjectName("lineEdit_find")
        self.horizontalLayout_m_top.addWidget(self.lineEdit_find)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_m_top.addItem(spacerItem1)
        self.toolButton_grid = QtWidgets.QToolButton(self.groupBox_middle)
        self.toolButton_grid.setText("")
        self.toolButton_grid.setCheckable(True)
        self.toolButton_grid.setChecked(True)
        self.toolButton_grid.setObjectName("toolButton_grid")
        self.horizontalLayout_m_top.addWidget(self.toolButton_grid)
        self.toolButton_list = QtWidgets.QToolButton(self.groupBox_middle)
        self.toolButton_list.setText("")
        self.toolButton_list.setCheckable(True)
        self.toolButton_list.setObjectName("toolButton_list")
        self.horizontalLayout_m_top.addWidget(self.toolButton_list)
        self.toolButton_dateils = QtWidgets.QToolButton(self.groupBox_middle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_dateils.sizePolicy().hasHeightForWidth())
        self.toolButton_dateils.setSizePolicy(sizePolicy)
        self.toolButton_dateils.setObjectName("toolButton_dateils")
        self.horizontalLayout_m_top.addWidget(self.toolButton_dateils)
        self.gridLayout_3.addLayout(self.horizontalLayout_m_top, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_middle, 1, 1, 1, 1)
        self.groupBox_right = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_right.sizePolicy().hasHeightForWidth())
        self.groupBox_right.setSizePolicy(sizePolicy)
        self.groupBox_right.setMaximumSize(QtCore.QSize(260, 16777215))
        self.groupBox_right.setTitle("")
        self.groupBox_right.setObjectName("groupBox_right")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_right)
        self.gridLayout_7.setObjectName("gridLayout_7")
        # self.listWidget_history = QtWidgets.QListWidget(self.groupBox_right)
        self.listWidget_history = my_list_widget.MenuListWidget()
        self.listWidget_history.setIconSize(QtCore.QSize(100, 100))
        self.listWidget_history.setObjectName("listWidget_history")
        self.gridLayout_7.addWidget(self.listWidget_history, 6, 0, 1, 1)
        self.frame_info = QtWidgets.QFrame(self.groupBox_right)
        self.frame_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_info)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")

        # task_lay = QtWidgets.QVBoxLayout()
        # self.gridLayout_7.addWidget(task_lay, 0, 0, 1, 1)
        label_task = QtWidgets.QLabel()
        label_task.setStyleSheet("color: rgb(255, 0, 0);")
        label_task.setText(u"任务备注：")
        # label_task.setFont(font)
        self.gridLayout_6.addWidget(label_task, 0, 0, 1, 1)
        # task_lay.addWidget(label_task)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label_task.sizePolicy().hasHeightForWidth())
        label_task.setSizePolicy(sizePolicy)

        self.label_task_info = QtWidgets.QLabel()
        self.label_task_info.setStyleSheet("color: rgb(255, 0, 0);")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_task_info.sizePolicy().hasHeightForWidth())
        self.label_task_info.setSizePolicy(sizePolicy)
        self.label_task_info.setText("")
        self.gridLayout_6.addWidget(self.label_task_info, 0, 1, 1, 1)
        # task_lay.addWidget(self.label_task_info)

        # version_lay = QtWidgets.QVBoxLayout()
        # self.gridLayout_7.addWidget(version_lay, 1, 0, 1, 1)
        label_version = QtWidgets.QLabel()
        label_version.setText(u"版本备注：")
        # label_version.setFont(font)
        self.gridLayout_6.addWidget(label_version, 1, 0, 1, 1)
        # version_lay.addWidget(label_version)
        # self.gridLayout_7.addWidget(label_version, 1, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label_version.sizePolicy().hasHeightForWidth())
        label_version.setSizePolicy(sizePolicy)

        self.label_version_info = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_version_info.sizePolicy().hasHeightForWidth())
        self.label_version_info.setSizePolicy(sizePolicy)
        self.label_version_info.setText("")
        self.gridLayout_6.addWidget(self.label_version_info, 1, 1, 1, 1)
        # version_lay.addWidget(self.label_version_info)
        # self.gridLayout_7.addWidget(self.label_version_info, 1, 1, 1, 1)


        self.verticalLayout_info_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_info_left.setObjectName("verticalLayout_info_left")
        self.label_name = QtWidgets.QLabel(self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setWeight(75)
        font.setBold(True)
        # self.label_name.setFont(font)
        # self.label_name.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_name.setObjectName("label_name")
        self.verticalLayout_info_left.addWidget(self.label_name)
        self.gridLayout_6.addLayout(self.verticalLayout_info_left, 2, 0, 1, 1)
        self.verticalLayout_info_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_info_right.setObjectName("verticalLayout_info_right")
        self.label_time = QtWidgets.QLabel(self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.verticalLayout_info_right.addWidget(self.label_time)
        self.gridLayout_6.addLayout(self.verticalLayout_info_right, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_info, 2, 0, 1, 1)
        # self.listWidget_no_version = QtWidgets.QListWidget(self.groupBox_right)
        self.listWidget_no_version = my_list_widget.MenuListWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_no_version.sizePolicy().hasHeightForWidth())
        self.listWidget_no_version.setSizePolicy(sizePolicy)
        self.listWidget_no_version.setIconSize(QtCore.QSize(100, 100))
        self.listWidget_no_version.setObjectName("listWidget_no_version")
        self.gridLayout_7.addWidget(self.listWidget_no_version, 4, 0, 1, 1)
        self.label_history = QtWidgets.QLabel(self.groupBox_right)
        self.label_history.setAlignment(QtCore.Qt.AlignCenter)
        self.label_history.setObjectName("label_history")
        self.gridLayout_7.addWidget(self.label_history, 3, 0, 1, 1)
        self.label_history_2 = QtWidgets.QLabel(self.groupBox_right)
        self.label_history_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_history_2.setObjectName("label_history_2")
        self.gridLayout_7.addWidget(self.label_history_2, 5, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_right, 1, 2, 1, 1)
        MainWindow_OCT_Loader_UI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_OCT_Loader_UI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 23))
        self.menubar.setObjectName("menubar")
        MainWindow_OCT_Loader_UI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_OCT_Loader_UI)
        self.statusbar.setObjectName("statusbar")
        MainWindow_OCT_Loader_UI.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_OCT_Loader_UI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_OCT_Loader_UI)

    def retranslateUi(self, MainWindow_OCT_Loader_UI):
        MainWindow_OCT_Loader_UI.setWindowTitle(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "十月: Loader", None, -1))
        self.label_icon.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "十月", None, -1))
        self.label_title.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "Loader", None, -1))
        self.treeWidget_project.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "1", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_project), QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "  当前项目  ", None, -1))
        self.treeWidget_task.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "1", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_task), QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", " 我的任务 ", None, -1))
        self.label_scale_min.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "-", None, -1))
        self.label_scale_max.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "+", None, -1))
        self.toolButton_dateils.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "Show Details", None, -1))
        self.label_name.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "更新信息", None, -1))
        self.label_history.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "无版本号文件", None, -1))
        self.label_history_2.setText(QtWidgets.QApplication.translate("MainWindow_OCT_Loader_UI", "有版本号文件", None, -1))

