# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'standardCameraForm.ui'
#
# Created: Wed Apr 26 12:22:25 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_standardCameraForm(object):
    def setupUi(self, standardCameraForm):
        standardCameraForm.setObjectName("standardCameraForm")
        standardCameraForm.resize(444, 484)
        self.layoutWidget = QtGui.QWidget(standardCameraForm)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 424, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_standardCamera = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_standardCamera.setMinimumSize(QtCore.QSize(421, 121))
        self.groupBox_standardCamera.setMaximumSize(QtCore.QSize(421, 121))
        self.groupBox_standardCamera.setObjectName("groupBox_standardCamera")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_standardCamera)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_createCamera = QtGui.QPushButton(self.groupBox_standardCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_createCamera.sizePolicy().hasHeightForWidth())
        self.pushButton_createCamera.setSizePolicy(sizePolicy)
        self.pushButton_createCamera.setObjectName("pushButton_createCamera")
        self.horizontalLayout_3.addWidget(self.pushButton_createCamera)
        self.pushButton_linkTwist = QtGui.QPushButton(self.groupBox_standardCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_linkTwist.sizePolicy().hasHeightForWidth())
        self.pushButton_linkTwist.setSizePolicy(sizePolicy)
        self.pushButton_linkTwist.setObjectName("pushButton_linkTwist")
        self.horizontalLayout_3.addWidget(self.pushButton_linkTwist)
        self.pushButton_lookAt = QtGui.QPushButton(self.groupBox_standardCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_lookAt.sizePolicy().hasHeightForWidth())
        self.pushButton_lookAt.setSizePolicy(sizePolicy)
        self.pushButton_lookAt.setCheckable(True)
        self.pushButton_lookAt.setObjectName("pushButton_lookAt")
        self.horizontalLayout_3.addWidget(self.pushButton_lookAt)
        self.pushButton_importExport = QtGui.QPushButton(self.groupBox_standardCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_importExport.sizePolicy().hasHeightForWidth())
        self.pushButton_importExport.setSizePolicy(sizePolicy)
        self.pushButton_importExport.setCheckable(True)
        self.pushButton_importExport.setObjectName("pushButton_importExport")
        self.horizontalLayout_3.addWidget(self.pushButton_importExport)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtGui.QLabel(self.groupBox_standardCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.label_cameraName = QtGui.QLabel(self.groupBox_standardCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cameraName.sizePolicy().hasHeightForWidth())
        self.label_cameraName.setSizePolicy(sizePolicy)
        self.label_cameraName.setText("")
        self.label_cameraName.setObjectName("label_cameraName")
        self.horizontalLayout_11.addWidget(self.label_cameraName)
        self.pushButton_update = QtGui.QPushButton(self.groupBox_standardCamera)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update.sizePolicy().hasHeightForWidth())
        self.pushButton_update.setSizePolicy(sizePolicy)
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout_11.addWidget(self.pushButton_update)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_standardCamera)
        self.groupBox_lookAtParameter = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_lookAtParameter.setMinimumSize(QtCore.QSize(421, 151))
        self.groupBox_lookAtParameter.setMaximumSize(QtCore.QSize(421, 151))
        self.groupBox_lookAtParameter.setObjectName("groupBox_lookAtParameter")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_lookAtParameter)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.widget = QtGui.QWidget(self.groupBox_lookAtParameter)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 16))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.radioButton_manual = QtGui.QRadioButton(self.widget)
        self.radioButton_manual.setChecked(True)
        self.radioButton_manual.setObjectName("radioButton_manual")
        self.horizontalLayout_7.addWidget(self.radioButton_manual)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.radioButton_auto = QtGui.QRadioButton(self.widget)
        self.radioButton_auto.setObjectName("radioButton_auto")
        self.horizontalLayout_6.addWidget(self.radioButton_auto)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.doubleSpinBox_distance = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_distance.setMinimum(0.1)
        self.doubleSpinBox_distance.setMaximum(1000.0)
        self.doubleSpinBox_distance.setSingleStep(1.0)
        self.doubleSpinBox_distance.setProperty("value", 5.0)
        self.doubleSpinBox_distance.setObjectName("doubleSpinBox_distance")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_distance)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.groupBox_lookAtParameter)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.widget_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 16))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.radioButton_smartBake = QtGui.QRadioButton(self.widget_2)
        self.radioButton_smartBake.setChecked(True)
        self.radioButton_smartBake.setObjectName("radioButton_smartBake")
        self.horizontalLayout_10.addWidget(self.radioButton_smartBake)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label = QtGui.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBox_tolerance = QtGui.QDoubleSpinBox(self.widget_2)
        self.doubleSpinBox_tolerance.setMaximum(1.0)
        self.doubleSpinBox_tolerance.setSingleStep(0.01)
        self.doubleSpinBox_tolerance.setProperty("value", 0.05)
        self.doubleSpinBox_tolerance.setObjectName("doubleSpinBox_tolerance")
        self.horizontalLayout.addWidget(self.doubleSpinBox_tolerance)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.radioButton_framesPerSample = QtGui.QRadioButton(self.widget_2)
        self.radioButton_framesPerSample.setObjectName("radioButton_framesPerSample")
        self.horizontalLayout_9.addWidget(self.radioButton_framesPerSample)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.pushButton_createLookAt = QtGui.QPushButton(self.groupBox_lookAtParameter)
        self.pushButton_createLookAt.setObjectName("pushButton_createLookAt")
        self.horizontalLayout_4.addWidget(self.pushButton_createLookAt)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_lookAtParameter)
        self.tabWidget_importExport = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget_importExport.setMinimumSize(QtCore.QSize(422, 101))
        self.tabWidget_importExport.setMaximumSize(QtCore.QSize(422, 101))
        self.tabWidget_importExport.setObjectName("tabWidget_importExport")
        self.tab_import = QtGui.QWidget()
        self.tab_import.setObjectName("tab_import")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_import)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_updatePath_import = QtGui.QPushButton(self.tab_import)
        self.pushButton_updatePath_import.setMinimumSize(QtCore.QSize(23, 23))
        self.pushButton_updatePath_import.setMaximumSize(QtCore.QSize(23, 23))
        self.pushButton_updatePath_import.setObjectName("pushButton_updatePath_import")
        self.horizontalLayout_8.addWidget(self.pushButton_updatePath_import)
        self.label_6 = QtGui.QLabel(self.tab_import)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_abcCacheFilePath_import = QtGui.QLineEdit(self.tab_import)
        self.lineEdit_abcCacheFilePath_import.setObjectName("lineEdit_abcCacheFilePath_import")
        self.horizontalLayout_8.addWidget(self.lineEdit_abcCacheFilePath_import)
        self.pushButton_abcCacheChoose_import = QtGui.QPushButton(self.tab_import)
        self.pushButton_abcCacheChoose_import.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_abcCacheChoose_import.setObjectName("pushButton_abcCacheChoose_import")
        self.horizontalLayout_8.addWidget(self.pushButton_abcCacheChoose_import)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.pushButton_abcCache_import = QtGui.QPushButton(self.tab_import)
        self.pushButton_abcCache_import.setObjectName("pushButton_abcCache_import")
        self.horizontalLayout_14.addWidget(self.pushButton_abcCache_import)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.gridLayout_7.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.tabWidget_importExport.addTab(self.tab_import, "")
        self.tab_export = QtGui.QWidget()
        self.tab_export.setObjectName("tab_export")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_export)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_updatePath_export = QtGui.QPushButton(self.tab_export)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_updatePath_export.sizePolicy().hasHeightForWidth())
        self.pushButton_updatePath_export.setSizePolicy(sizePolicy)
        self.pushButton_updatePath_export.setMinimumSize(QtCore.QSize(23, 23))
        self.pushButton_updatePath_export.setMaximumSize(QtCore.QSize(23, 23))
        self.pushButton_updatePath_export.setObjectName("pushButton_updatePath_export")
        self.horizontalLayout_2.addWidget(self.pushButton_updatePath_export)
        self.label_2 = QtGui.QLabel(self.tab_export)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_abcCacheFilePath_export = QtGui.QLineEdit(self.tab_export)
        self.lineEdit_abcCacheFilePath_export.setObjectName("lineEdit_abcCacheFilePath_export")
        self.horizontalLayout_2.addWidget(self.lineEdit_abcCacheFilePath_export)
        self.pushButton_abcCacheChoose_export = QtGui.QPushButton(self.tab_export)
        self.pushButton_abcCacheChoose_export.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_abcCacheChoose_export.setObjectName("pushButton_abcCacheChoose_export")
        self.horizontalLayout_2.addWidget(self.pushButton_abcCacheChoose_export)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.pushButton_abcCache_export = QtGui.QPushButton(self.tab_export)
        self.pushButton_abcCache_export.setObjectName("pushButton_abcCache_export")
        self.horizontalLayout_13.addWidget(self.pushButton_abcCache_export)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.tabWidget_importExport.addTab(self.tab_export, "")
        self.verticalLayout_3.addWidget(self.tabWidget_importExport)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem15)

        self.retranslateUi(standardCameraForm)
        QtCore.QMetaObject.connectSlotsByName(standardCameraForm)

    def retranslateUi(self, standardCameraForm):
        standardCameraForm.setWindowTitle(QtGui.QApplication.translate("standardCameraForm", "Standard Camera V1.05b by GoodRun", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_standardCamera.setTitle(QtGui.QApplication.translate("standardCameraForm", "Standard Camera:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_createCamera.setText(QtGui.QApplication.translate("standardCameraForm", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_linkTwist.setText(QtGui.QApplication.translate("standardCameraForm", "Link\n"
"Twist", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_lookAt.setText(QtGui.QApplication.translate("standardCameraForm", "Look\n"
"At", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_importExport.setText(QtGui.QApplication.translate("standardCameraForm", "Import\n"
"Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("standardCameraForm", "Camera Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_update.setText(QtGui.QApplication.translate("standardCameraForm", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_lookAtParameter.setTitle(QtGui.QApplication.translate("standardCameraForm", "Look At Parameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("standardCameraForm", "Parameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_manual.setText(QtGui.QApplication.translate("standardCameraForm", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_auto.setText(QtGui.QApplication.translate("standardCameraForm", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("standardCameraForm", "Distance: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("standardCameraForm", "Bake Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_smartBake.setText(QtGui.QApplication.translate("standardCameraForm", "Smart Bake", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("standardCameraForm", "Tolerance: ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_framesPerSample.setText(QtGui.QApplication.translate("standardCameraForm", "Frames per Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_createLookAt.setText(QtGui.QApplication.translate("standardCameraForm", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_updatePath_import.setText(QtGui.QApplication.translate("standardCameraForm", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("standardCameraForm", "Alembic Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_abcCacheChoose_import.setText(QtGui.QApplication.translate("standardCameraForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_abcCache_import.setText(QtGui.QApplication.translate("standardCameraForm", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_importExport.setTabText(self.tabWidget_importExport.indexOf(self.tab_import), QtGui.QApplication.translate("standardCameraForm", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_updatePath_export.setText(QtGui.QApplication.translate("standardCameraForm", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("standardCameraForm", "Alembic Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_abcCacheChoose_export.setText(QtGui.QApplication.translate("standardCameraForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_abcCache_export.setText(QtGui.QApplication.translate("standardCameraForm", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_importExport.setTabText(self.tabWidget_importExport.indexOf(self.tab_export), QtGui.QApplication.translate("standardCameraForm", "Export", None, QtGui.QApplication.UnicodeUTF8))

