pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["animator.htm","For Animator","MG-Picker Studio animator mode: The UI of animator mode is designed to be as simple as possible, to save the workspace for animator. The power of ...",""],
["animatorinteractivity.htm","Animator Interactivity","Animator interactivity: MG-Picker provide powerful and very rich ways for animator to interactive with pickers. Maker sure you are in animator int...",""],
["codesnippets.htm","Code Snippets","Code snippets are a block of codes to speed up the coding process. In the code editor of attribute editor, for example, the command of a command-b...",""],
["commandbuttonpresets.htm","Command Button Presets","Command button presets are a bunch of scripts to speed up the command button creating process. Those preset scripts enable you to create command b...",""],
["converters.htm","Converters","Converters are a MEL script that convert other type of picker node / file into MG-Picker file / node. The converters utilizes the MEL API commands...",""],
["customeloaderandlister.htm","Loader and Lister","If you wanna: - Grab any part of your scene rig, based on selected rig&#39;s namespace, MG-Picker studio is able to auto-load a picker file, setup nam...",""],
["designer.htm","For Designer","MG-Picker Studio designer mode: The ui of MG-Picker Studio designer mode may seems \"complicated\", because so many buttons, fields and menus. Howev...",""],
["designprinciple.htm","Design Principle","Design Principle of pickers: There are no rules for designing a picker, you are free to use your imagination to create you pickers. Yet if you kee...",""],
["distributeinpipeline.htm","Distribute Pickers in Pipeline","MG-Picker Studio searchs 3 Basic paths and any count of other paths for the desired picker: Fully Inside maya scene. The picker could be stored in...",""],
["editing.htm","Editing","Basically, we use the edit tool , transform tool , copy/paste Properties tool to do all the editing. Transform Items You could move the item, set ...",""],
["hotkeys_anim.htm","Hotkeys","To use picker hotkeys in animator mode: Since MG-Picker Studio v1.6, picker hotkeys for animator mode are reduced to minimum set. Most of time, yo...",""],
["hotkeys_designer.htm","Hotkeys","To use picker hotkeys in designer mode: All you need is activate the picker window. As long as it is activated, all hotkeys are picker hotkeys. To...",""],
["install.htm","Install MG-PickerStudio","First to MG-Picker Studio： 1.Visit http://twincodes.com or http://mgland.com to download the latest MG-PickerStudio release package and extract it...",""],
["itemshapes.htm","Item Shapes","Item shapes: A picker item, which could be select-button, command-button, slider, attribute-button, text or panel, all of them contain a shape of ...",""],
["itemtypes.htm","Item Types","Currently there are 6 types of picker item: Select-Button : Select-Button is for maya selection, it contains a list of objects as members. You cou...",""],
["links.htm","Links","There are two types of links: - Parent Link: Parent link is only available for select-buttons and the slider handles (which are actually also sele...",""],
["loadpicker.htm","Loading Pickers","Many different ways to quickly load desired Pickers: 1.By default, all in-scene picker nodes will be loaded automatically a maya scene is opened. ...",""],
["mg-picker_english_ftsearch.htm","MG-Picker Studio Manual","Enter keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): &#169; 2017 MGLAND animation studio You must have JavaScript enabled to use this versio...",""],
["mgimageprocesser.htm","MGImageProcesser Command","command (MEL/Python) MGImageProcesser Go to: MEL synopsis . Python synopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis...",""],
["mgpicker.htm","MGPicker Command","command (MEL/Python) MGPicker Go to: MEL synopsis . Python synopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis MGPicke...",""],
["mgpickeritem.htm","MGPickerItem Command","command (MEL/Python) MGPickerItem Go to: MEL synopsis . Python snopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis MGPi...",""],
["mgpickerlink.htm","MGPickerLink Command","command (MEL/Python) MGPickerLink Go to: MEL synopsis . Python synopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis MGP...",""],
["mgpickermenu.htm","MGPickerMenu Command","command (MEL/Python) MGPickerMenu Go to: MEL synopsis . Python synopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis MGP...",""],
["mgpickermenuitem.htm","MGPickerMenuItem Command","command (MEL/Python) MGPickerMenuItem Go to: MEL synopsis . Python synopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis...",""],
["mgpickerservice.htm","MGPickerService Command","command (MEL/Python) MGPickerService Go to: MEL synopsis . Python synopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis ...",""],
["mgpickerview.htm","MGPickerView Command","command (MEL/Python) MGPickerView Go to: MEL synopsis . Python synopsis . Return value . Flags . MEL examples . Python examples . MEL Synopsis MGP...",""],
["mgselecthelper.htm","MG-Select Helper","MG-Select Helper: It is tool window that stores your temporary selection, serves a selection assistant. You could have any number of select helper...",""],
["more_resource.htm","More Resources","The pickers for popular free maya rigs: http://twincodes.com/MGPicker_en.html?url=Download Video tutorials: http://twincodes.com/MGPicker_en.html ",""],
["namespace.htm","Namespace","Set current picker&#39;s namespace： Namespace is the naming prefix for current picker, changing of namspace enables you use picker on different rigs a...",""],
["pickermenu.htm","Picker Menu","Every picker item could be attached a left clicking / right clicking menu. - To attach / edit a picker item&#39;s menu: Select the picker item, go to ...",""],
["pickertoolintergration.htm","Picker Tool Intergration","Tips for controlling different MG-Picker Studio versions: Why we need to that: Big studio might has their own software packing &#38; managing tool and...",""],
["programmer.htm","For Programmer","MG-Picker Studio could helps you to design powerful picker even you know nothing about programming. Yet if you know MEL / Python scripting in Maya...",""],
["publishinternet.htm","Publish to Internet","If you are a rigger that want to publish your rig, pickers to internet: Select Picker Menu / Publish Current Picker.. The picker publish dialog wi...",""],
["quickworkflow.htm","Quick Workflow","Quick picker design workflow: - Choice #1: Create picker from a existing picker template: -3 ways to create picker from template: 1. ALT+LMB doubl...",""],
["q__a.htm","Q &#38; A","Q: How to avoid hard-coding the picker item id ? To get the id of current picker item, say you are editing the command of command-button of the id...",""],
["setnamespace.htm","Set Namespace","Set current picker&#39;s namespace： Namespace is the naming prefix for current picker, changing of namspace enables you use picker on different rigs a...",""],
["simpleediting.htm","Simple Editing","Simple creating &#38; editing feature in animator mode: To create simple picker item or edit them for temporary use, you could press \"W\" key to switch...",""],
["syncvaluewithmaya.htm","Sync Value With Maya","For Maya Attribute Button &#38; Sliders: For attr-button that controls maya attribute, or sliders that control maya attributes, you don&#39;t need to writ...",""],
["tipsforanimator.htm","Tips For Animator","Tips for using the MG-Picker Studio in animator mode: Use \"Ctrl+F\" hotkey and \"Escape\" hotkey to turn on / off the attribute searching widget. In ...",""],
["tipsfordesigner.htm","Tips For Designer","Tips for using the MG-Picker Studio in designer mode: These is tool-tip for each menu items, UI buttons, property setting widgets. Read them to kn...",""],
["tipsforprogrammer.htm","Tips For Programmer","Tips for the programming in MG-Picker Studio : Frequently visited commands be made into command button, and parent them to the picker panel. For t...",""],
["viewportmanipulation.htm","Viewport Manipulation","Picker view manipulation: -MG-Picker view adopt the very similar rules as you interactive with Maya&#39;s 3d viewport: MMB: Pan the view, with/without...",""],
["welcome.htm","Welcome","Welcome to MG-Picker Studio ! MG-Picker Studio is a very intuitive and animator friendly maya picker tool, with the a powerful feature that enable...",""]];
