# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputUI.ui'
#
# Created: Thu Mar 28 11:01:39 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 526)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_project = QtWidgets.QComboBox(Dialog)
        self.comboBox_project.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_project.setObjectName("comboBox_project")
        self.horizontalLayout_5.addWidget(self.comboBox_project)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.comboBox_scene = QtWidgets.QComboBox(Dialog)
        self.comboBox_scene.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_scene.setObjectName("comboBox_scene")
        self.horizontalLayout_5.addWidget(self.comboBox_scene)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.comboBox_name = QtWidgets.QComboBox(Dialog)
        self.comboBox_name.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_name.setObjectName("comboBox_name")
        self.horizontalLayout_5.addWidget(self.comboBox_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.comboBox_fromgroup = QtWidgets.QComboBox(Dialog)
        self.comboBox_fromgroup.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_fromgroup.setObjectName("comboBox_fromgroup")
        self.horizontalLayout_4.addWidget(self.comboBox_fromgroup)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.comboBox_ver = QtWidgets.QComboBox(Dialog)
        self.comboBox_ver.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_ver.setObjectName("comboBox_ver")
        self.horizontalLayout_4.addWidget(self.comboBox_ver)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_path.setReadOnly(True)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_path)
        self.pushButton_setpath = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setpath.sizePolicy().hasHeightForWidth())
        self.pushButton_setpath.setSizePolicy(sizePolicy)
        self.pushButton_setpath.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_setpath.setObjectName("pushButton_setpath")
        self.horizontalLayout_2.addWidget(self.pushButton_setpath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.spinBox_startframe = QtWidgets.QSpinBox(Dialog)
        self.spinBox_startframe.setMinimumSize(QtCore.QSize(45, 20))
        self.spinBox_startframe.setFrame(True)
        self.spinBox_startframe.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_startframe.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_startframe.setMinimum(-999)
        self.spinBox_startframe.setMaximum(99999)
        self.spinBox_startframe.setObjectName("spinBox_startframe")
        self.horizontalLayout_3.addWidget(self.spinBox_startframe)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.spinBox_endframe = QtWidgets.QSpinBox(Dialog)
        self.spinBox_endframe.setMinimumSize(QtCore.QSize(45, 20))
        self.spinBox_endframe.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_endframe.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_endframe.setMinimum(-999)
        self.spinBox_endframe.setMaximum(99999)
        self.spinBox_endframe.setObjectName("spinBox_endframe")
        self.horizontalLayout_3.addWidget(self.spinBox_endframe)

        self.spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(self.spacer)

        self.merge_mod_lb = QtWidgets.QLabel(Dialog)
        self.merge_mod_lb.setText(u"缓存融合方式")
        self.horizontalLayout_3.addWidget(self.merge_mod_lb)

        self.if_blend_cb = QtWidgets.QComboBox(Dialog)
        # self.if_blend_cb.setText(u'缓存融合方式')
        self.if_blend_cb.addItem('')
        self.if_blend_cb.addItem('BlendShape')
        self.if_blend_cb.addItem('Merge')
        self.horizontalLayout_3.addWidget(self.if_blend_cb)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout_6.addWidget(self.treeWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_loadsetup = QtWidgets.QPushButton(Dialog)
        self.pushButton_loadsetup.setMinimumSize(QtCore.QSize(0, 75))
        self.pushButton_loadsetup.setObjectName("pushButton_loadsetup")
        self.verticalLayout_2.addWidget(self.pushButton_loadsetup)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pushButton_loadasset = QtWidgets.QPushButton(Dialog)
        self.pushButton_loadasset.setMinimumSize(QtCore.QSize(0, 75))
        self.pushButton_loadasset.setObjectName("pushButton_loadasset")
        self.verticalLayout_2.addWidget(self.pushButton_loadasset)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.pushButton_loadcache = QtWidgets.QPushButton(Dialog)
        self.pushButton_loadcache.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_loadcache.setObjectName("pushButton_loadcache")
        self.verticalLayout_2.addWidget(self.pushButton_loadcache)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.label_text = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text.sizePolicy().hasHeightForWidth())
        self.label_text.setSizePolicy(sizePolicy)
        self.label_text.setObjectName("label_text")
        self.horizontalLayout.addWidget(self.label_text)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Abc 缓存导入", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "项目名称：", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "场次：", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "镜号：", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "来源环节：", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "版本：", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "配置文件：", None, -1))
        self.pushButton_setpath.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "时间范围：", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "开始帧：", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "结束帧：", None, -1))
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("Dialog", "引用资产", None, -1))
        self.treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("Dialog", "目标资产", None, -1))
        self.treeWidget.headerItem().setText(2, QtWidgets.QApplication.translate("Dialog", "目标环节", None, -1))
        self.treeWidget.headerItem().setText(3, QtWidgets.QApplication.translate("Dialog", "导入UV", None, -1))
        self.treeWidget.headerItem().setText(4, QtWidgets.QApplication.translate("Dialog", "导入缓存", None, -1))
        self.treeWidget.headerItem().setText(5, QtWidgets.QApplication.translate("Dialog", "缓存来源", None, -1))
        self.treeWidget.headerItem().setText(6, QtWidgets.QApplication.translate("Dialog", "缓存版本", None, -1))
        self.treeWidget.headerItem().setText(7, QtWidgets.QApplication.translate("Dialog", "提示", None, -1))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("Dialog", "CHAR", None, -1))
        self.treeWidget.topLevelItem(1).setText(0, QtWidgets.QApplication.translate("Dialog", "PROP", None, -1))
        self.treeWidget.topLevelItem(2).setText(0, QtWidgets.QApplication.translate("Dialog", "ENV", None, -1))
        self.treeWidget.topLevelItem(3).setText(0, QtWidgets.QApplication.translate("Dialog", "CAM", None, -1))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_loadsetup.setText(QtWidgets.QApplication.translate("Dialog", "加载配置", None, -1))
        self.pushButton_loadasset.setText(QtWidgets.QApplication.translate("Dialog", "加载资产", None, -1))
        self.pushButton_loadcache.setText(QtWidgets.QApplication.translate("Dialog", "载入缓存", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "进度：", None, -1))
        self.label_text.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))

