# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'outputUI.ui'
#
# Created: Thu Mar 28 11:01:38 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1003, 412)
        Dialog.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.comboBox_project = QtWidgets.QComboBox(Dialog)
        self.comboBox_project.setMinimumSize(QtCore.QSize(120, 20))
        self.comboBox_project.setObjectName("comboBox_project")
        self.horizontalLayout_4.addWidget(self.comboBox_project)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_taskname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_taskname.setMinimumSize(QtCore.QSize(0, 20))
        # self.lineEdit_taskname.setReadOnly(True)
        self.lineEdit_taskname.setObjectName("lineEdit_taskname")
        self.horizontalLayout_4.addWidget(self.lineEdit_taskname)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lineEdit_taskver = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_taskver.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_taskver.setReadOnly(True)
        self.lineEdit_taskver.setObjectName("lineEdit_taskver")
        self.horizontalLayout_4.addWidget(self.lineEdit_taskver)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.comboBox_pathTyp = QtWidgets.QComboBox(Dialog)
        self.comboBox_pathTyp.setObjectName("comboBox_pathTyp")
        self.comboBox_pathTyp.addItem("")
        self.comboBox_pathTyp.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_pathTyp)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_path.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_path.setReadOnly(True)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_path)
        self.pushButton_setpath = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setpath.sizePolicy().hasHeightForWidth())
        self.pushButton_setpath.setSizePolicy(sizePolicy)
        self.pushButton_setpath.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_setpath.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_setpath.setObjectName("pushButton_setpath")
        self.horizontalLayout_2.addWidget(self.pushButton_setpath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_startframe = QtWidgets.QSpinBox(Dialog)
        self.spinBox_startframe.setMinimumSize(QtCore.QSize(45, 20))
        self.spinBox_startframe.setFrame(True)
        self.spinBox_startframe.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_startframe.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_startframe.setMinimum(-999)
        self.spinBox_startframe.setMaximum(99999)
        self.spinBox_startframe.setObjectName("spinBox_startframe")
        self.horizontalLayout_3.addWidget(self.spinBox_startframe)
        self.pushButton_setstartframe = QtWidgets.QPushButton(Dialog)
        self.pushButton_setstartframe.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_setstartframe.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_setstartframe.setObjectName("pushButton_setstartframe")
        self.horizontalLayout_3.addWidget(self.pushButton_setstartframe)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_endframe = QtWidgets.QSpinBox(Dialog)
        self.spinBox_endframe.setMinimumSize(QtCore.QSize(45, 20))
        self.spinBox_endframe.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_endframe.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_endframe.setMinimum(-999)
        self.spinBox_endframe.setMaximum(99999)
        self.spinBox_endframe.setObjectName("spinBox_endframe")
        #
        # self.if_blend = QtWidgets.QCheckBox(Dialog)
        # # self.spinBox_endframe.setMinimumSize(QtCore.QSize(45, 20))
        # # self.spinBox_endframe.setAlignment(QtCore.Qt.AlignCenter)
        # # self.spinBox_endframe.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        # # self.spinBox_endframe.setMinimum(-999)
        # # self.spinBox_endframe.setMaximum(99999)
        # self.if_blend.setChecked(1)
        # self.spinBox_endframe.setObjectName("spinBox_endframe")

        self.horizontalLayout_3.addWidget(self.spinBox_endframe)
        self.pushButton_setendframe = QtWidgets.QPushButton(Dialog)
        self.pushButton_setendframe.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_setendframe.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_setendframe.setObjectName("pushButton_setendframe")
        self.horizontalLayout_3.addWidget(self.pushButton_setendframe)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_init = QtWidgets.QPushButton(Dialog)
        self.pushButton_init.setMinimumSize(QtCore.QSize(0, 75))
        self.pushButton_init.setObjectName("pushButton_init")
        self.verticalLayout_2.addWidget(self.pushButton_init)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_saveInfo = QtWidgets.QPushButton(Dialog)
        self.pushButton_saveInfo.setMinimumSize(QtCore.QSize(0, 75))
        self.pushButton_saveInfo.setObjectName("pushButton_saveInfo")
        self.verticalLayout_2.addWidget(self.pushButton_saveInfo)
        self.pushButton_output = QtWidgets.QPushButton(Dialog)
        self.pushButton_output.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_output.setObjectName("pushButton_output")
        self.verticalLayout_2.addWidget(self.pushButton_output)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.label_text = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text.sizePolicy().hasHeightForWidth())
        self.label_text.setSizePolicy(sizePolicy)
        self.label_text.setObjectName("label_text")
        self.horizontalLayout_5.addWidget(self.label_text)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Abc 缓存导出", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "当前项目：", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "当前任务：", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "任务版本：", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "路径类型：", None, -1))
        self.comboBox_pathTyp.setItemText(0, QtWidgets.QApplication.translate("Dialog", "任务名", None, -1))
        self.comboBox_pathTyp.setItemText(1, QtWidgets.QApplication.translate("Dialog", "自定义", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "输出路径：", None, -1))
        self.pushButton_setpath.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "时间范围：", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "开始帧：", None, -1))
        self.pushButton_setstartframe.setText(QtWidgets.QApplication.translate("Dialog", "Set", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "结束帧：", None, -1))
        self.pushButton_setendframe.setText(QtWidgets.QApplication.translate("Dialog", "Set", None, -1))
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("Dialog", "引用文件", None, -1))
        self.treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("Dialog", "版本", None, -1))
        self.treeWidget.headerItem().setText(2, QtWidgets.QApplication.translate("Dialog", "是否输出", None, -1))
        self.treeWidget.headerItem().setText(3, QtWidgets.QApplication.translate("Dialog", "缓存导出路径", None, -1))
        self.treeWidget.headerItem().setText(4, QtWidgets.QApplication.translate("Dialog", "提示", None, -1))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("Dialog", "CHAR", None, -1))
        self.treeWidget.topLevelItem(1).setText(0, QtWidgets.QApplication.translate("Dialog", "PROP", None, -1))
        self.treeWidget.topLevelItem(2).setText(0, QtWidgets.QApplication.translate("Dialog", "ENV", None, -1))
        self.treeWidget.topLevelItem(3).setText(0, QtWidgets.QApplication.translate("Dialog", "CAM", None, -1))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_init.setText(QtWidgets.QApplication.translate("Dialog", "初始化", None, -1))
        self.pushButton_saveInfo.setText(QtWidgets.QApplication.translate("Dialog", "保存配置", None, -1))
        self.pushButton_output.setText(QtWidgets.QApplication.translate("Dialog", "输出缓存", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "进度：", None, -1))
        self.label_text.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))

